<div class="row">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <ul class="nav nav-tabs">
            <li class="<?php echo ($controller == 'vigattinads\controller\dashboard\admin') ? 'active' : ''; ?>"><a href="/vigattinads/dashboard/admin">Home</a></li>
            <li class="<?php echo ($controller == 'vigattinads\controller\dashboard\admin\manageaccount') ? 'active' : ''; ?>"><a href="/vigattinads/dashboard/admin/manageaccount">Manage Account</a></li>
            <li class="<?php echo ($controller == 'vigattinads\controller\dashboard\admin\manageads') ? 'active' : ''; ?>"><a href="/vigattinads/dashboard/admin/manageads">Manage Ads</a></li>
            <li class="<?php echo ($controller == 'vigattinads\controller\dashboard\admin\historylog') ? 'active' : ''; ?>"><a href="/vigattinads/dashboard/admin/historylog">History Logs</a></li>
        </ul>
    </div>
</div>
<?php echo $content; ?>