<br />
<br />
<div class="row">
    <div class="col-lg-2 col-md-2 col-sm-2 col-xs-2"></div>
    <div class="col-lg-8 col-md-8 col-sm-8 col-xs-8">
        <form action="/vigattinads/dashboard/admin/manageads" method="post" class="form-horizontal search-form1">
            <div class="input-group">
                <div class="input-group-btn">
                    <button class="btn btn-default dropdown-toggle category-switch" data-toggle="dropdown"><?php echo $this->escapeHtml($adsSearchCategory); ?> <span class="caret"></span></button>
                    <ul class="dropdown-menu">
                        <li><a class="item" href="/vigattinads/dashboard/admin/manageads/reset">Show All</a></li>
                        <li><a class="item" href="javascript:">Title</a></li>
                        <li><a class="item" href="javascript:">Username</a></li>
                        <li><a class="item" href="javascript:">Email</a></li>
                        <li><a class="item" href="javascript:">First Name</a></li>
                        <li><a class="item" href="javascript:">Last Name</a></li>
                    </ul>
                </div>
                <input type="text" class="form-control search-input" placeholder="type text here" name="adsSearchValue" value="<?php echo $this->escapeHtmlAttr($adsSearchValue); ?>">
                <input class="category-hidden-input" type="hidden" name="adsSearchCategory" value="<?php echo $this->escapeHtmlAttr($adsSearchCategory); ?>">
                <span class="input-group-btn">
                    <button class="btn btn-default" type="submit" name="adsSearch" value="user">Search</button>
                </span>
            </div>
            <div class="input-group">
                <label class="checkbox-inline">
                    <input type="radio" name="searchFilter" value="100" <?php if($adsSearchFilter == 100) echo 'checked="checked"'; ?> class="" title="Search filter"> <span class="text-success legend">All</span>
                </label>
                <label class="checkbox-inline">
                    <input type="radio" name="searchFilter" value="<?php echo \VigattinAds\DomainModel\Ads::STATUS_APPROVED; ?>" <?php if($adsSearchFilter == \VigattinAds\DomainModel\Ads::STATUS_APPROVED) echo 'checked="checked"'; ?> class="" title="Search filter"> <span class="text-success legend">Approved</span>
                </label>
                <label class="checkbox-inline">
                    <input type="radio" name="searchFilter" value="<?php echo \VigattinAds\DomainModel\Ads::STATUS_PENDING; ?>" <?php if($adsSearchFilter == \VigattinAds\DomainModel\Ads::STATUS_PENDING) echo 'checked="checked"'; ?> class="" title="Search filter"> <span class="text-warning legend">Pending</span>
                </label>
                <label class="checkbox-inline">
                    <input type="radio" name="searchFilter" value="<?php echo \VigattinAds\DomainModel\Ads::STATUS_REVIEWING; ?>" <?php if($adsSearchFilter == \VigattinAds\DomainModel\Ads::STATUS_REVIEWING) echo 'checked="checked"'; ?> class="" title="Search filter"> <span class="text-warning legend">Reviewing</span>
                </label>
                <label class="checkbox-inline">
                    <input type="radio" name="searchFilter" value="<?php echo \VigattinAds\DomainModel\Ads::STATUS_DISAPPROVED; ?>" <?php if($adsSearchFilter == \VigattinAds\DomainModel\Ads::STATUS_DISAPPROVED) echo 'checked="checked"'; ?> class="" title="Search filter"> <span class="text-danger legend">Disapprove</span>
                </label>
                <label class="checkbox-inline">
                    <input type="radio" name="searchFilter" value="<?php echo \VigattinAds\DomainModel\Ads::STATUS_PAUSED; ?>" <?php if($adsSearchFilter == \VigattinAds\DomainModel\Ads::STATUS_PAUSED) echo 'checked="checked"'; ?> class="" title="Search filter"> <span class="text-warning legend">Paused</span>
                </label>
            </div>
        </form>
    </div>
    <div class="col-lg-2 col-md-2 col-sm-2 col-xs-2"></div>
</div>
<p></p>
<!-- Account list -->
<div class="row">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <div class="table-responsive">
            <div>Ads List</div>
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Status</th>
                        <th>Website</th>
                        <th>Title</th>
                        <th>Reserve</th>
                        <th>Username</th>
                        <th>Email</th>
                        <th>First name</th>
                        <th>Last name</th>
                        <th>Options</th>
                    </tr>
                </thead>
                <tbody class="ads-list-tbody">
                    <?php foreach($paginator as $key => $ads): ?>
                    <tr id="adsrow<?php echo $ads->get('id'); ?>">
                        <td><?php echo $paginationCount + ($key + 1); ?></td>
                        <td class="data-status">
                            <?php switch(intval($ads->get('status'))):
                                case \VigattinAds\DomainModel\Ads::STATUS_APPROVED: ?>
                                    <span class="text-success"><span class="glyphicon glyphicon-ok"></span></span>
                                    <?php break;
                                case \VigattinAds\DomainModel\Ads::STATUS_PENDING: ?>
                                    <span class="text-warning"><span class="glyphicon glyphicon-warning-sign"></span></span>
                                    <?php break;
                                case \VigattinAds\DomainModel\Ads::STATUS_DISAPPROVED: ?>
                                    <span class="text-danger"><span class="glyphicon glyphicon-ban-circle"></span></span>
                                    <?php break;
                                case \VigattinAds\DomainModel\Ads::STATUS_PAUSED: ?>
                                    <span class="text-warning"><span class="glyphicon glyphicon-pause"></span></span>
                                    <?php break;
                                case \VigattinAds\DomainModel\Ads::STATUS_REVIEWING: ?>
                                    <span class="text-warning"><span class="glyphicon glyphicon-search"></span></span>
                                    <?php break;
                            endswitch; ?>
                        </td>
                        <td class="data-website"><?php echo $this->escapeHtml($ads->get('showIn')); ?></td>
                        <td class="data-last-title"><?php echo $this->escapeHtml($ads->get('adsTitle')); ?></td>
                        <td class="data-reserve"><?php echo intval($ads->get('viewLimit')); ?></td>
                        <td class="data-username"><?php echo $this->escapeHtml($ads->get('userUsername')); ?></td>
                        <td class="data-email"><?php echo $this->escapeHtml($ads->get('userEmail')); ?></td>
                        <td class="data-first-name"><?php echo ucwords(strtolower($this->escapeHtml($ads->get('userFirstName')))); ?></td>
                        <td class="data-last-name"><?php echo ucwords(strtolower($this->escapeHtml($ads->get('userLastName')))); ?></td>
                        <td>
                            <a
                                href="javascript:"
                                class="option-manage-ads"
                                data-toggle="modal"
                                data-target="#adminAdsForm"
                                target-id="#adsrow<?php echo $ads->get('id'); ?>"
                                adsId="<?php echo $ads->get('id'); ?>"
                                adsTitle="<?php echo $this->escapeHtmlAttr($ads->get('adsTitle')); ?>"
                                adsDescription="<?php echo $this->escapeHtmlAttr($ads->get('adsDescription')); ?>"
                                adsStatus="<?php echo intval($ads->get('status')); ?>"
                                adsImage="<?php echo $this->escapeHtmlAttr($ads->get('adsImage')); ?>"
                                adsUrl="<?php echo $this->escapeHtmlAttr($ads->get('adsUrl')); ?>"
                                adsPrice="<?php echo $this->escapeHtmlAttr($ads->get('adsPrice')); ?>"
                            >Review</a>
                        </td>
                    </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
            <div class="legend">
                <span class="text-success"><span class="glyphicon glyphicon-ok"></span> Approve</span>&nbsp;&nbsp;
                <span class="text-warning"><span class="glyphicon glyphicon-warning-sign"></span> Pending</span>&nbsp;
                <span class="text-warning"><span class="glyphicon glyphicon-search"></span> Reviewing</span>&nbsp;
                <span class="text-danger"><span class="glyphicon glyphicon-ban-circle"></span> Disapprove</span>&nbsp;
                <span class="text-warning"><span class="glyphicon glyphicon-pause"></span> Paused</span>
            </div>
        </div>
    </div>
</div>

<div class="text-center">
    <?php echo $this->paginationControl($paginator, 'Sliding', 'vigattinads/view/paginator/bootstrapPagination', array('route' => 'vigattinads_dashboard_admin_manageads')); ?>
</div>

<!-- Modal Edit Ads -->
<div class="modal fade" id="adminAdsForm" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title" id="myModalLabel"><span class="dynamic-title">Manage Ads</span></h4>
            </div>
            <form role="form">
                <div class="modal-body">
                    <div class="row admin-ads-manage-preview">
                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 ads-live-preview-label"><strong>Ads Preview</strong><p></p></div>
                            <div class="col-lg-2 col-md-2 col-sm-2 col-xs-2"></div>
                            <div class="col-lg-8 col-md-8 col-sm-8 col-xs-8">
                                <div class="row ads-frame">
                                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 ads-frame-title">Ads Title</div>
                                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 ads-frame-price">Php <span class="price-value">100.00</span></div>
                                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12"><div class="ads-image-preview-container"></div><span class="ads-frame-description">Ads description</span></div>
                                    <div class="clearfix"></div>
                                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12"><a class="ads-frame-url" href=""></a></div>
                                </div>
                            </div>
                            <div class="col-lg-2 col-md-2 col-sm-2 col-xs-2"></div>
                        </div>
                    </div>
                    <hr>
                    <div class="row admin-change-status-container">
                        <!--
                        <div class="col-xs-12 text-center">Change ads status</div>
                        <div class="col-xs-12 text-center">
                            <input class="status-radio status1" type="radio" name="status" value="1"> <span class="text-success"><span class="glyphicon glyphicon-ok"></span></span>&nbsp;&nbsp;
                            <input class="status-radio status0" type="radio" name="status" value="0"> <span class="text-warning"><span class="glyphicon glyphicon-warning-sign"></span></span>&nbsp;&nbsp;
                            <input class="status-radio status-1" type="radio" name="status" value="-1"> <span class="text-danger"><span class="glyphicon glyphicon-ban-circle"></span></span>&nbsp;&nbsp;
                            <input class="status-radio status2" type="radio" name="status" value="2"> <span class="text-warning"><span class="glyphicon glyphicon-pause"></span></span>
                        </div>
                        <!--
                        <p></p>
                        <div class="col-xs-12 text-center">
                            <textarea class="status-reason" placeholder="reason about the change"></textarea>
                        </div>
                        -->
                        <p></p>
                        <div class="col-xs-12 text-center">
                            <button type="button" class="btn btn-warning status-apply" value="pending">Change to Pending</button>
                            <img style="display: none;" class="account-form-progress" src="/assets/vigattinads/img/circle-preloader-2.gif" />
                        </div>
                    </div>
                    <hr>
                    <div class="row">
                        <div class="col-xs-10 col-xs-offset-1 ads-history-container">
                            <div class="ads-history-title">History</div>
                            <div class="ads-history-log"></div>
                            <div class="ads-history-control text-center">
                                <img style="display: none;" class="account-form-progress" src="/assets/vigattinads/img/circle-preloader-2.gif" />
                            </div>
                        </div>
                    </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                </div>
            </form>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->