<br />
<br />
<div class="row">
    <div class="col-lg-2 col-md-2 col-sm-2 col-xs-2"></div>
    <div class="col-lg-8 col-md-8 col-sm-8 col-xs-8">
        <form action="" method="post" class="form-horizontal search-form1">

        </form>
    </div>
    <div class="col-lg-2 col-md-2 col-sm-2 col-xs-2"></div>
</div>
<p></p>
<!-- Account list -->
<div class="row">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <div class="table-responsive">
            <div>History Log list (<?php echo $paginator->getTotalItemCount(); ?>)</div>
            <table class="table table-bordered">
                <thead>
                <tr>
                    <th>#</th>
                    <th>Description</th>
                    <th>Date</th>
                    <th>Committed By</th>
                    <th>Target</th>
                </tr>
                </thead>
                <tbody class="">
                    <?php foreach($paginator as $key => $log): ?>
                        <?php $msgArray = explode(',', $log['logMessage']); ?>
                        <tr id="adsrow<?php echo $log['id']; ?>">
                            <td><?php echo $paginationCount + ($key + 1); ?></td>
                            <td><?php echo $this->escapeHtml($msgArray[3]); ?></td>
                            <td><?php echo date('D, d M Y H:i:s', $log['timeCreated']); ?></td>
                            <td><?php echo $this->escapeHtml($msgArray[2]); ?></td>
                            <td><?php echo (!empty($msgArray[4])) ? $this->escapeHtml($msgArray[4]) : $log['targetUserId']; ?></td>
                        </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>
</div>
<!-- Paginator -->
<div class="text-center">
    <?php echo $this->paginationControl($paginator, 'Sliding', 'vigattinads/view/paginator/bootstrapPagination', array('route' => 'vigattinads_dashboard_admin_historylog')); ?>
</div>