<br />
<br />
<div class="row">
    <div class="col-lg-2 col-md-2 col-sm-2 col-xs-2"></div>
    <div class="col-lg-8 col-md-8 col-sm-8 col-xs-8">
        <form action="/vigattinads/dashboard/admin/manageads" method="post" class="search-form1">
            <div class="input-group">
                <div class="input-group-btn">
                    <button class="btn btn-default dropdown-toggle category-switch" data-toggle="dropdown"><?php echo $this->escapeHtml($adsSearchCategory); ?> <span class="caret"></span></button>
                    <ul class="dropdown-menu">
                        <li><a class="item" href="/vigattinads/dashboard/admin/manageads/reset">Show All</a></li>
                        <li><a class="item" href="javascript:">Title</a></li>
                        <li><a class="item" href="javascript:">Username</a></li>
                        <li><a class="item" href="javascript:">Email</a></li>
                        <li><a class="item" href="javascript:">First Name</a></li>
                        <li><a class="item" href="javascript:">Last Name</a></li>
                    </ul>
                </div>
                <input type="text" class="form-control search-input" placeholder="type text here" name="adsSearchValue" value="<?php echo $this->escapeHtmlAttr($adsSearchValue); ?>">
                <input class="category-hidden-input" type="hidden" name="adsSearchCategory" value="<?php echo $this->escapeHtmlAttr($adsSearchCategory); ?>">
                <span class="input-group-btn">
                    <button class="btn btn-default" type="submit" name="adsSearch" value="user">Search</button>
                </span>
            </div>
        </form>
    </div>
    <div class="col-lg-2 col-md-2 col-sm-2 col-xs-2"></div>
</div>
<p></p>
<!-- Account list -->
<div class="row">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <div class="table-responsive">
            <div>Ads List</div>
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Status</th>
                        <th>Title</th>
                        <th>Reserve</th>
                        <th>Username</th>
                        <th>Email</th>
                        <th>First name</th>
                        <th>Last name</th>
                        <th>Options</th>
                    </tr>
                </thead>
                <tbody class="ads-list-tbody">
                    <?php foreach($paginator as $key => $ads): ?>
                    <tr id="<?php echo $ads->get('id'); ?>">
                        <td><?php echo $key+1; ?></td>
                        <td class="data-status">
                            <?php switch(intval($ads->get('status'))):
                                case \VigattinAds\DomainModel\Ads::STATUS_APPROVED: ?>
                                    <span class="text-success"><span class="glyphicon glyphicon-ok"></span></span>
                                    <?php break;
                                case \VigattinAds\DomainModel\Ads::STATUS_PENDING: ?>
                                    <span class="text-warning"><span class="glyphicon glyphicon-warning-sign"></span></span>
                                    <?php break;
                                case \VigattinAds\DomainModel\Ads::STATUS_DISAPPROVED: ?>
                                    <span class="text-danger"><span class="glyphicon glyphicon-ban-circle"></span></span>
                                    <?php break;
                                case \VigattinAds\DomainModel\Ads::STATUS_PAUSED: ?>
                                    <span class="text-warning"><span class="glyphicon glyphicon-pause"></span></span>
                                    <?php break;
                                case \VigattinAds\DomainModel\Ads::STATUS_REVIEWING: ?>
                                    <span class="text-warning"><span class="glyphicon glyphicon-search"></span></span>
                                    <?php break;
                            endswitch; ?>
                        </td>
                        <td class="data-last-title"><?php echo $this->escapeHtml($ads->get('adsTitle')); ?></td>
                        <td class="data-reserve"><?php echo intval($ads->get('viewLimit')); ?></td>
                        <td class="data-username"><?php echo $this->escapeHtml($ads->get('userUsername')); ?></td>
                        <td class="data-email"><?php echo $this->escapeHtml($ads->get('userEmail')); ?></td>
                        <td class="data-first-name"><?php echo ucwords(strtolower($this->escapeHtml($ads->get('userFirstName')))); ?></td>
                        <td class="data-last-name"><?php echo ucwords(strtolower($this->escapeHtml($ads->get('userLastName')))); ?></td>
                        <td><a href="javascript:" class="option-view-ads" data-toggle="modal" data-target="#adsForm" target-id="<?php echo $ads->get('id'); ?>"><span class="glyphicon glyphicon-edit"></span> View</a></td>
                    </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
            <div class="legend">
                <span class="text-success"><span class="glyphicon glyphicon-ok"></span> Approve</span>&nbsp;&nbsp;
                <span class="text-warning"><span class="glyphicon glyphicon-warning-sign"></span> Pending</span>&nbsp;
                <span class="text-warning"><span class="glyphicon glyphicon-search"></span> Reviewing</span>&nbsp;
                <span class="text-danger"><span class="glyphicon glyphicon-ban-circle"></span> Disapprove</span>&nbsp;
                <span class="text-warning"><span class="glyphicon glyphicon-pause"></span> Paused</span>
            </div>
        </div>
    </div>
</div>

<div class="text-center">
    <?php echo $this->paginationControl($paginator, 'Sliding', 'vigattinads/view/paginator/bootstrapPagination', array('route' => 'vigattinads_dashboard_admin_manageads')); ?>
</div>

<!-- Modal Create new account -->
<div class="modal fade" id="accountForm" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title" id="myModalLabel"><span class="dynamic-title">Account Form</span> <img style="display: none;" class="account-form-progress" src="/assets/vigattinads/img/circle-preloader-2.gif" /></h4>
            </div>
            <form role="form">
                <div class="modal-body">
                    <div class="form-group">
                        <div class="form-error form-error-email text-danger"><small></small></div>
                        <input title="Email" type="email" class="form-control tooltip-enable-right" id="inputEmail1" placeholder="Email">
                    </div>
                    <div class="form-group">
                        <div class="form-error form-error-username text-danger"><small></small></div>
                        <input title="Username" type="text" class="form-control tooltip-enable-right" id="inputUsername1" placeholder="Username">
                    </div>
                    <div class="form-group">
                        <div class="form-error form-error-password text-danger"><small></small></div>
                        <input title="Password" type="password" class="form-control tooltip-enable-right" id="inputPassword1" placeholder="Password">
                    </div>
                    <div class="form-group">
                        <div class="form-error form-error-repeat-password text-danger"><small></small></div>
                        <input title="Repeat password" type="password" class="form-control tooltip-enable-right" id="inputRepeatPassword1" placeholder="Repeat password">
                    </div>
                    <div class="form-group">
                        <div class="form-error form-error-first-name text-danger"><small></small></div>
                        <input title="First name" type="text" class="form-control tooltip-enable-right" id="inputFirstName1" placeholder="First name">
                    </div>
                    <div class="form-group">
                        <div class="form-error form-error-last-name text-danger"><small></small></div>
                        <input title="Last name" type="text" class="form-control tooltip-enable-right" id="inputLastName1" placeholder="Last name">
                    </div>
                    <div class="form-group">
                        <div class="form-error form-error-gold text-danger"><small></small></div>
                        <input title="Gold" type="number" class="form-control tooltip-enable-right" id="inputGold1" placeholder="Gold" value="0">
                    </div>
                    <div class="form-group">
                        <p><input type="checkbox" id="inputPrivilegeB1" disabled="disabled"> <small>(B) Basic usage</small></p>
                        <p><input type="checkbox" id="inputPrivilegeA1"> <small>(A) Admin</small></p>
                        <p><input type="checkbox" id="inputPrivilegeP1"> <small>(P) Approve ads</small></p>
                    </div>
                    <input type="hidden" name="id" id="inputId1" class="form-control">
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-primary submit-action" id="inputSubmit1">Create</button>
                    <button type="button" class="btn btn-danger delete-action" id="inputDelete1">Delete</button>
                </div>
            </form>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->