<div class="row">
    <div class="col-xs-12"><h4>Import template from Vigattin Trade</h4></div>
    <?php if($website == \VigattinAds\Controller\Dashboard\Ads\Create\ChooseWebsite\ChooseWebsiteController::TOURISMBLOGGER): ?>
        <?php $redirectUrl = $this->url('vigattinads_dashboard_ads_create_choose_website_blogger_import_edit'); ?>
        <?php $this->headScript()->prependScript('var importUrl = "'.$redirectUrl.'"'); ?>
    <?php else: ?>
        <?php $redirectUrl = $this->url('vigattinads_dashboard_ads_create_choose_website_import_edit'); ?>
        <?php $this->headScript()->prependScript('var importUrl = "'.$redirectUrl.'"'); ?>
    <?php endif; ?>
    <div class="col-xs-8">
        <div class="alert alert-info">
            <span class="text-warning">You may skip this part if you want to compose your own ads or you do not have any ads on vigattintrade.com. If you click skip your ads editor will start with a fresh empty template.</span>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-xs-2">
        <a class="btn btn-default" href="<?php echo $this->url('vigattinads_dashboard_ads_create_choose_website'); ?>">Back</a>
        <form class="inline-block" method="post" action="">
            <input type="hidden" name="redirect-url" value="<?php echo $redirectUrl; ?>">
            <button type="submit" name="action" value="save-session" class="btn btn-default">Skip</button>
        </form>
    </div>
</div>
<hr>
<div class="row">
    <div class="col-sm-12 col-md-8">
        <ul class="ads-import-list auto-load"">

        </ul>
        <div class="text-center"><button type="button" class="btn btn-default import-ads-list-more-button">More</button><img  class="import-ads-list-progress" src="/assets/vigattinads/img/circle-preloader-2.gif" /></div>
    </div>
</div>