<div class="row">
    <div class="col-xs-12"><h4>Import template from Vigattin Trade</h4></div>
</div>
<div class="row">
    <div class="col-xs-12">
        <p><a class="btn btn-default" href="<?php echo $this->url('vigattinads_dashboard_ads_create_choose_website'); ?>">Back</a></p>
    </div>
</div>
<hr>
<div class="row">
    <div class="col-sm-12 col-md-8">
        <ul class="ads-import-list auto-load"">

        </ul>
        <div class="text-center"><button type="button" class="btn btn-default import-ads-list-more-button">More</button><img  class="import-ads-list-progress" src="/assets/vigattinads/img/circle-preloader-2.gif" /></div>
    </div>
</div>