<?php if($ads instanceof \VigattinAds\DomainModel\Ads): ?>
<div class="row">
    <div class="col-xs-12">
        <!--
        <div class="thumbnail" style="width: 60px">
            <img src="/assets/vigattinads/img/logo-vig.jpg" alt="vigattin">
        </div>
        -->
        <div class="panel-group" id="accordion">
            <div class="panel panel-info">
                <div class="panel-heading">
                    <h4 class="panel-title">
                        <span>current target site is</span> <span class="text-warning"><?php echo $ads->get('showIn'); ?></span>
                        <p></p>
                        <a class="btn btn-default" data-toggle="collapse" data-parent="#accordion" href="#collapseOne">
                            Change target site
                        </a>
                    </h4>
                </div>
                <div id="collapseOne" class="panel-collapse collapse">
                    <div class="panel-body">
                        Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod. Brunch 3 wolf moon tempor, sunt aliqua put a bird on it squid single-origin coffee nulla assumenda shoreditch et. Nihil anim keffiyeh helvetica, craft beer labore wes anderson cred nesciunt sapiente ea proident. Ad vegan excepteur butcher vice lomo. Leggings occaecat craft beer farm-to-table, raw denim aesthetic synth nesciunt you probably haven't heard of them accusamus labore sustainable VHS.
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<hr>
<?php endif; ?>