<?php if($ads instanceof \VigattinAds\DomainModel\Ads): ?>
<div class="row">
    <div class="col-xs-12">
        <div class="panel-group" id="accordion">
            <div class="panel panel-info">
                <div class="panel-heading">
                    <h4 class="panel-title">
                        <span>current target site is</span> <span class="text-warning"><?php echo $showIn; ?></span>
                        <p></p>
                        <a title="Choose which website your ads will appear" class="btn btn-default tooltip-enable-right" data-toggle="collapse" data-parent="#accordion" href="#collapseOne">
                            Change target site
                        </a>
                    </h4>
                </div>
                <div id="collapseOne" class="panel-collapse collapse">
                    <div class="panel-body">
                        <div class="row choose-website-container">

                            <!-- vigattin.com -->
                            <div class="col-xs-4 col-sm-3 col-md-2">
                                <?php if($showIn == \VigattinAds\Controller\Dashboard\Ads\Create\ChooseWebsite\ChooseWebsiteController::VIGATTIN): ?>
                                    <div class="thumbnail opacity-50" title="<?php echo \VigattinAds\Controller\Dashboard\Ads\Create\ChooseWebsite\ChooseWebsiteController::VIGATTIN; ?>">
                                        <img src="/assets/vigattinads/img/logo-vig.jpg" alt="<?php echo \VigattinAds\Controller\Dashboard\Ads\Create\ChooseWebsite\ChooseWebsiteController::VIGATTIN; ?>">
                                    </div>
                                <?php else: ?>
                                    <a class="thumbnail" href="<?php echo $this->url('vigattinads_dashboard_ads_edit', array('controller' => 'change-site', 'param1' => $ads->get('id'), 'param2' => 'vigattin.com')); ?>"  title="<?php echo \VigattinAds\Controller\Dashboard\Ads\Create\ChooseWebsite\ChooseWebsiteController::VIGATTIN; ?>">
                                        <img src="/assets/vigattinads/img/logo-vig.jpg" alt="<?php echo \VigattinAds\Controller\Dashboard\Ads\Create\ChooseWebsite\ChooseWebsiteController::VIGATTIN; ?>">
                                    </a>
                                <?php endif; ?>
                            </div>
                            <!-- /vigattin.com -->

                            <!-- vigattintrade.com -->
                            <div class="col-xs-4 col-sm-3 col-md-2">
                                <?php if($showIn == \VigattinAds\Controller\Dashboard\Ads\Create\ChooseWebsite\ChooseWebsiteController::VIGATTINTRADE): ?>
                                    <div class="thumbnail opacity-50" title="<?php echo \VigattinAds\Controller\Dashboard\Ads\Create\ChooseWebsite\ChooseWebsiteController::VIGATTINTRADE; ?>">
                                        <img src="/assets/vigattinads/img/logo-trade.jpg" alt="<?php echo \VigattinAds\Controller\Dashboard\Ads\Create\ChooseWebsite\ChooseWebsiteController::VIGATTINTRADE; ?>">
                                    </div>
                                <?php else: ?>
                                    <a class="thumbnail" href="<?php echo $this->url('vigattinads_dashboard_ads_edit', array('controller' => 'change-site', 'param1' => $ads->get('id'), 'param2' => \VigattinAds\Controller\Dashboard\Ads\Create\ChooseWebsite\ChooseWebsiteController::VIGATTINTRADE)); ?>" title="<?php echo \VigattinAds\Controller\Dashboard\Ads\Create\ChooseWebsite\ChooseWebsiteController::VIGATTINTRADE; ?>">
                                        <img src="/assets/vigattinads/img/logo-trade.jpg" alt="<?php echo \VigattinAds\Controller\Dashboard\Ads\Create\ChooseWebsite\ChooseWebsiteController::VIGATTINTRADE; ?>">
                                    </a>
                                <?php endif; ?>
                            </div>
                            <!-- /vigattintrade.com -->

                            <!-- vigattintourism.com -->
                            <div class="col-xs-4 col-sm-3 col-md-2">
                                <?php if($showIn == \VigattinAds\Controller\Dashboard\Ads\Create\ChooseWebsite\ChooseWebsiteController::VIGATTINTOURISM): ?>
                                    <div class="thumbnail opacity-50" title="<?php echo \VigattinAds\Controller\Dashboard\Ads\Create\ChooseWebsite\ChooseWebsiteController::VIGATTINTOURISM; ?>">
                                        <img src="/assets/vigattinads/img/logo-tourism.jpg" alt="<?php echo \VigattinAds\Controller\Dashboard\Ads\Create\ChooseWebsite\ChooseWebsiteController::VIGATTINTOURISM; ?>">
                                    </div>
                                <?php else: ?>
                                    <a class="thumbnail" href="<?php echo $this->url('vigattinads_dashboard_ads_edit', array('controller' => 'change-site', 'param1' => $ads->get('id'), 'param2' => \VigattinAds\Controller\Dashboard\Ads\Create\ChooseWebsite\ChooseWebsiteController::VIGATTINTOURISM)); ?>" title="<?php echo \VigattinAds\Controller\Dashboard\Ads\Create\ChooseWebsite\ChooseWebsiteController::VIGATTINTOURISM; ?>">
                                        <img src="/assets/vigattinads/img/logo-tourism.jpg" alt="<?php echo \VigattinAds\Controller\Dashboard\Ads\Create\ChooseWebsite\ChooseWebsiteController::VIGATTINTOURISM; ?>">
                                    </a>
                                <?php endif; ?>
                            </div>
                            <!-- /vigattintourism.com -->

                            <!-- vigattintourism bloggers -->
                            <div class="col-xs-4 col-sm-3 col-md-2">
                                <?php if($showIn == \VigattinAds\Controller\Dashboard\Ads\Create\ChooseWebsite\ChooseWebsiteController::TOURISMBLOGGER): ?>
                                    <div class="thumbnail opacity-50" title="<?php echo \VigattinAds\Controller\Dashboard\Ads\Create\ChooseWebsite\ChooseWebsiteController::TOURISMBLOGGER; ?>">
                                        <img src="/assets/vigattinads/img/logo-bloggers.jpg" alt="<?php echo \VigattinAds\Controller\Dashboard\Ads\Create\ChooseWebsite\ChooseWebsiteController::TOURISMBLOGGER; ?>">
                                    </div>
                                <?php else: ?>
                                    <a class="thumbnail" href="<?php echo $this->url('vigattinads_dashboard_ads_edit', array('controller' => 'change-site', 'param1' => $ads->get('id'), 'param2' => \VigattinAds\Controller\Dashboard\Ads\Create\ChooseWebsite\ChooseWebsiteController::TOURISMBLOGGER)); ?>" title="<?php echo \VigattinAds\Controller\Dashboard\Ads\Create\ChooseWebsite\ChooseWebsiteController::TOURISMBLOGGER; ?>">
                                        <img src="/assets/vigattinads/img/logo-bloggers.jpg" alt="<?php echo \VigattinAds\Controller\Dashboard\Ads\Create\ChooseWebsite\ChooseWebsiteController::TOURISMBLOGGER; ?>">
                                    </a>
                                <?php endif; ?>
                            </div>
                            <!-- /vigattintourism bloggers -->

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<?php endif; ?>