<?php echo $this->headTitle('Dashboard'); ?>
<div class="row">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 big-font-2em">
        Welcome <?php echo $this->escapeHtml($firstName.' '.$lastName); ?>
    </div>
</div>
<div class="row">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <hr>
    </div>
</div>
<div class="row dashboard-number-status">
    <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
        <div>current gold</div> <span class="big-font-3em"><?php echo $credit; ?></span>
    </div>
    <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
        <div>approved ads</div> <span class="big-font-3em text-success"><?php echo $approvedAds->count(); ?></span>
    </div>
    <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
        <div>pending ads</div> <span class="big-font-3em text-warning"><?php echo $pendingAds->count(); ?></span>
    </div>
    <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
        <div>disapproved ads</div> <span class="big-font-3em text-danger"><?php echo $disapprovedAds->count(); ?></span>
    </div>
</div>
<div class="row">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <hr>
    </div>
</div>
<div class="row">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <ul class="nav nav-tabs">
            <li class="<?php echo ($activeTab == 'vigattintrade') ? 'active' : ''; ?>"><a href="/vigattinads/dashboard/vigattintrade">Vigattintrade</a></li>
            <!-- <li class="<?php echo ($activeTab == 'test') ? 'active' : ''; ?>"><a href="/vigattinads/dashboard/test">Test</a></li> -->
        </ul>
    </div>
</div>
<br />
<div class="row">
    <div class="col-sm-12 col-md-8">
        <ul class="ads-import-list auto-load" target-page="<?php echo $activeTab; ?>">

        </ul>
        <div class="text-center"><button type="button" class="btn btn-default import-ads-list-more-button">More</button><img  class="import-ads-list-progress" src="/assets/vigattinads/img/circle-preloader-2.gif" /></div>
    </div>
</div>