<div class="form-group">
    <label class="control-label">Vigattintourism Directory <small class="text-warning">Choose which directory the ads will appear</small></label>
    <ul class="list-group list-unstyled">
        <li>
            <a class="ads-preview-link" target="_blank" href="http://vigattintourism.com#preview">preview</a>
            <input class="tourism-cat-checkbox must-have-one-checked" type="checkbox" style="margin-left: 10px" name="selectedKeyword[0]" value="(homepage)" checked="checked"> Homepage
        </li>
        <li>
            <a class="ads-preview-link" target="_blank" href="http://vigattintourism.com/tourism/destinations#preview">preview</a>
            <input class="tourism-cat-checkbox must-have-one-checked" type="checkbox" style="margin-left: 10px" name="selectedKeyword[1]" value="(destination)" checked="checked"> Destination
        </li>
        <li>
            <a class="ads-preview-link" target="_blank" href="http://vigattintourism.com/tourism/articles?page=1#preview">preview</a>
            <input class="tourism-cat-checkbox must-have-one-checked" type="checkbox" style="margin-left: 10px" name="selectedKeyword[2]" value="(articles)" checked="checked"> Articles
        </li>
        <li>
            <a class="ads-preview-link" target="_blank" href="http://vigattintourism.com/tourism/tourist_spots#preview">preview</a>
            <input class="tourism-cat-checkbox must-have-one-checked" type="checkbox" style="margin-left: 10px" name="selectedKeyword[3]" value="(tourist spots)" checked="checked"> Tourist Spots
        </li>
        <li>
            <a class="ads-preview-link" target="_blank" href="http://vigattintourism.com/tourism/discussion#preview">preview</a>
            <input class="tourism-cat-checkbox must-have-one-checked" type="checkbox" style="margin-left: 10px" name="selectedKeyword[4]" value="(discussion)" checked="checked"> Discussion
        </li>
        <li>
            <a class="ads-preview-link" target="_blank" href="http://vigattintourism.com/tourism/destinations/91/directory#preview">preview</a>
            <input class="tourism-cat-checkbox must-have-one-checked" type="checkbox" style="margin-left: 10px" name="selectedKeyword[5]" value="(directory)" checked="checked"> Directory
        </li>
    </ul>
</div>