<div class="form-group">
    <label class="control-label">Vigattin Directory <small class="text-warning">Choose which directory the ads will appear</small></label>
    <ul class="list-group list-unstyled">
        <li>
            <a class="ads-preview-link" target="_blank" href="http://vigattin.com#preview">preview</a>
            <input class="tourism-cat-checkbox must-have-one-checked" type="checkbox" style="margin-left: 10px" name="selectedKeyword[]" value="Homepage" checked="checked"> Homepage
        </li>
    </ul>
</div>