<?php echo (isset($authorMenu)) ? $authorMenu : '';  ?>
<div class="form-group">
    <label class="control-label"><?php echo $title; ?> <small class="text-warning"><?php echo $description; ?></small></label>
    <ul class="list-group list-unstyled">
        <?php $groupName = ''; ?>
        <?php foreach($adsCategories as $key => $adsCategory): ?>
            <!-- Generate sub category title -->
            <?php if($adsCategory->getGroup() && ($adsCategory->getGroup() !== $groupName)): ?>
                <?php $groupName = $adsCategory->getGroup(); ?>
                <li style="margin-top: 5px;"><strong><?php echo $adsCategory->getGroup(); ?></strong></li>
            <?php endif; ?>
            <!-- /Generate sub category title -->
            <li>
                <a class="ads-preview-link" target="_blank" href="<?php echo $adsCategory->getPreviewLink(); ?>">preview</a>
                <input class="tourism-cat-checkbox must-have-one-checked" type="checkbox" style="margin-left: 10px" name="selectedCategory[<?php echo $key; ?>]" value="<?php echo $adsCategory->getKeyword(); ?>" <?php echo $adsCategory->getSelected() ? 'checked="checked"' : ''; ?> <?php echo $adsCategory->getDisable() ? 'disabled="disabled"': ''; ?>> <?php echo $adsCategory->getTitle(); ?>
            </li>
        <?php endforeach; ?>
    </ul>
</div>