<div>
    <p><b>Choose New Category</b></p>
    <button type="button" class="btn btn-default" data-toggle="modal" data-target="#tradeChangeCategoryModal">Choose Category</button>
</div>
<br>

<!-- Modal -->
<div class="modal fade" id="tradeChangeCategoryModal" tabindex="-1" role="dialog" aria-labelledby="tradeChangeCategoryModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                <h4 class="modal-title" id="tradeChangeCategoryModalLabel">Choose Category</h4>
            </div>
            <div class="modal-body">
                <!-- modal body -->
                <?php echo \VigattinAds\DomainModel\VigattinTrade\CatMap::generateAccordion(\VigattinAds\DomainModel\VigattinTrade\CatMap::$categoryMap); ?>
                <!-- /modal body -->
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <!--<button type="button" class="btn btn-primary">Save changes</button>-->
            </div>
        </div>
    </div>
</div>