<div class="row">
    <div class="col-xs-12"><h3>I want my ads to appear in...</h3></div>
</div>
<div class="row choose-website-container">
    <div class="col-lg-3 col-md-3 col-sm-3 col-xs-12">
        <a class="thumbnail" href="choose-website/choose/tourism" title="vigattintourism.com">
            <img src="/assets/vigattinads/img/logo-tourism.jpg" alt="vigattin tourism">
        </a>
    </div>
    <div class="col-lg-3 col-md-3 col-sm-3 col-xs-12">
        <a class="thumbnail" href="choose-website/choose/trade" title="vigattintourism.com">
            <img src="/assets/vigattinads/img/logo-tourism.jpg" alt="vigattin tourism">
        </a>
    </div>
    <div class="col-lg-3 col-md-3 col-sm-3 col-xs-12">
        <a class="thumbnail" href="choose-website/choose/vigattin" title="vigattintourism.com">
            <img src="/assets/vigattinads/img/logo-tourism.jpg" alt="vigattin tourism">
        </a>
    </div>
</div>