<div class="row">
    <div class="col-xs-12"><h4>Allowed category for vigattintourism.com are the following.</h4></div>
</div>
<div class="row">
    <div class="col-xs-12">
        <ul class="list-unstyled">
            <li>Homepage</li>
            <li>Destination</li>
            <li>Articles</li>
            <li>Tourist Spots</li>
            <li>Discussion</li>
            <li>Directory</li>
        </ul>
    </div>
</div>
<div class="row">
    <div class="col-xs-12">
        <a class="btn btn-default" href="/vigattinads/dashboard/ads/create/choose-website">Back</a> <a class="btn btn-default" href="/vigattinads/dashboard/ads/info">Next</a>
    </div>
</div>
