<div class="row">
    <div class="col-xs-12"><h3>I want my ads to appear in...</h3></div>
</div>
<div class="row choose-website-container">
    <div class="col-xs-4 col-sm-3 col-md-2">
        <a class="thumbnail" href="<?php echo $this->url('vigattinads_dashboard_ads_create', array('controller' => 'choose-website', 'action' => 'choose', 'param' => 'vigattin')); ?>" title="vigattin.com">
            <img src="/assets/vigattinads/img/logo-vig.jpg" alt="vigattin">
        </a>
    </div>
    <div class="col-xs-4 col-sm-3 col-md-2">
        <a class="thumbnail" href="<?php echo $this->url('vigattinads_dashboard_ads_create', array('controller' => 'choose-website', 'action' => 'choose', 'param' => 'trade')); ?>" title="vigattintrade.com">
            <img src="/assets/vigattinads/img/logo-trade.jpg" alt="vigattin trade">
        </a>
    </div>
    <div class="col-xs-4 col-sm-3 col-md-2">
        <a class="thumbnail" href="<?php echo $this->url('vigattinads_dashboard_ads_create', array('controller' => 'choose-website', 'action' => 'choose', 'param' => 'tourism')); ?>" title="vigattintourism.com">
            <img src="/assets/vigattinads/img/logo-tourism.jpg" alt="vigattin tourism">
        </a>
    </div>
    <div class="col-xs-4 col-sm-3 col-md-2">
        <a class="thumbnail" href="<?php echo $this->url('vigattinads_dashboard_ads_create', array('controller' => 'choose-website', 'action' => 'choose', 'param' => 'tourism-bloggers')); ?>" title="vigattintourism bloggers">
            <img src="/assets/vigattinads/img/logo-bloggers.jpg" alt="vigattintourism bloggers">
        </a>
    </div>
    <div class="hide col-xs-4 col-sm-3 col-md-2">
        <a class="thumbnail" href="<?php echo $this->url('vigattinads_dashboard_ads_create', array('controller' => 'choose-website', 'action' => 'choose', 'param' => 'deals')); ?>" title="vigattindeals.com">
            <img src="/assets/vigattinads/img/logo-deals.jpg" alt="vigattin deals">
        </a>
    </div>
</div>