<div class="row">
    <div class="col-xs-12"><h4>Allowed category for vigattintrade.com are the following.</h4></div>
</div>
<div class="row">
    <div class="col-xs-12">
        <ul class="list-unstyled">
            <?php foreach($categories as $category): ?>
                <li><?php echo $this->escapeHtml($category); ?></li>
            <?php endforeach; ?>
        </ul>
    </div>
</div>
<div class="row">
    <div class="col-xs-12">
        <a class="btn btn-default" href="/vigattinads/dashboard/ads/create/choose-website">Back</a> <a class="btn btn-default" href="/vigattinads/dashboard/ads/info">Next</a>
    </div>
</div>