<?php
/** @var \VigattinAds\DomainModel\Tourism\AuthorCollection $authors */
/** @var \VigattinAds\DomainModel\Tourism\Author $author */
/** @var \VigattinAds\DomainModel\Tourism\ArticleCategoryCollection $categories */
/** @var \VigattinAds\DomainModel\Tourism\ArticleCategory $category */
?>
<div class="row">
    <div class="col-xs-12 col-sm-12 col-md-8 col-lg-7">
        <form class="form-group has-feedback" method="post" action="" id="authorSearchForm">
            <!--
            <label class="control-label sr-only" for="inputTourismSearchAuthor">Search author</label>
            <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">Action <span class="caret"></span></button>
            <input type="text" class="form-control" placeholder="search author" id="inputTourismSearchAuthor" name="searchString" value="<?php echo $this->escapeHtmlAttr($searchString); ?>">
            <span class="glyphicon glyphicon-search form-control-feedback" style="cursor: pointer" onclick="$('#authorSearchForm').submit()"></span>
            -->

            <div class="input-group">
                <div class="input-group-btn">
                    <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">Categories <span class="caret"></span></button>
                    <ul class="dropdown-menu disable-toggle" role="menu">
                        <?php foreach($categories as $key => $category): ?>
                        <li>
                            <a class="checkbox">
                                <label>
                                    <input class="authorSearchCategories" type="checkbox" <?php echo isset($_POST['filter'][$key]) ? 'checked' : ''; ?> name="filter[<?php echo $key; ?>]" value="<?php echo $this->escapeHtmlAttr($category->getCategoryId()); ?>"> <?php echo $this->escapeHtml(ucfirst(strtolower($category->getCategoryName()))); ?>
                                </label>
                            </a>
                        </li>
                        <?php endforeach; ?>
                    </ul>
                </div>
                <input id="authorSearchString" type="text" class="form-control" placeholder="search author" name="searchString" value="<?php echo $this->escapeHtmlAttr($searchString); ?>">
                <div class="input-group-btn">
                    <button id="authorSearchSubmit" type="submit" class="btn btn-default" >Search</button>
                </div>
            </div>

        </form>
    </div>
    <div class="clearfix"></div>
    <div class="fluid-result-container col-xs-12">
            <table class="table table-striped">
                <thead>
                <tr>
                    <th>Photo</th>
                    <th>First Name</th>
                    <th>Last Name</th>
                    <th>Action</th>
                </tr>
                </thead>
                <tfoot>
                    <tr id="authorSearchTablePreloader">
                        <td colspan="4" class="text-center"><img src="/assets/vigattinads/img/circle-preloader-2.gif"></td>
                    </tr>
                </tfoot>
                <tbody id="authorSearchTable">
                <?php foreach($authors as $key => $author): ?>
                    <tr>
                        <td><div style="height: 50px; width: 50px; background-size: contain; background-image: url('<?php echo $this->escapeHtmlAttr($author->getPhotoUrl()); ?>')"></div></td>
                        <td><?php echo $this->escapeHtml($author->getFirstName()); ?></td>
                        <td><?php echo $this->escapeHtml($author->getLastName()); ?></td>
                        <td>
                            <form method="post" action="">
                                <button class="btn btn-default" type="submit" name="authorId" value="<?php echo $author->getId(); ?>">select</button>
                                <input type="hidden" name="authorFirstName" value="<?php echo $this->escapeHtmlAttr($author->getFirstName()); ?>">
                                <input type="hidden" name="authorLastName" value="<?php echo $this->escapeHtmlAttr($author->getLastName()); ?>">
                            </form>
                        </td>
                    </tr>
                <?php endforeach; ?>
                </tbody>
            </table>
    </div>
</div>