<div class="row">
    <div class="col-xs-6">
        <div class="form-group has-feedback">
            <label class="control-label sr-only" for="inputTourismSearchAuthor">Search author</label>
            <input type="text" class="form-control" placeholder="search author" id="inputTourismSearchAuthor">
            <span class="glyphicon glyphicon-search form-control-feedback"></span>
        </div>
    </div>
    <div class="clearfix"></div>
    <div class="fluid-result-container col-xs-12">
        <table class="table table-striped">
            <thead>
            <tr>
                <th><a href="#">#</a></th>
                <th><a href="#">First Name</a></th>
                <th><a href="#">Last Name</a></th>
                <th><a href="#">Username</a></th>
                <th><a href="#">Action</a></th>
            </tr>
            </thead>
            <tbody>
            <tr>
                <td>1</td>
                <td>Mark</td>
                <td>Otto</td>
                <td>mdo</td>
                <td><a class="btn btn-default" href="/vigattinads/dashboard/ads/create/choose-website/blogger-author/import">select</a></td>
            </tr>
            <tr>
                <td>2</td>
                <td>Jacob</td>
                <td>Thornton</td>
                <td>fat</td>
                <td><a class="btn btn-default" href="/vigattinads/dashboard/ads/create/choose-website/blogger-author/import">select</a></td>
            </tr>
            <tr>
                <td>3</td>
                <td>Larry</td>
                <td>the Bird</td>
                <td>twitter</td>
                <td><a class="btn btn-default" href="/vigattinads/dashboard/ads/create/choose-website/blogger-author/import">select</a></td>
            </tr>
            </tbody>
        </table>
    </div>
</div>