<form method="post" action="">
    <?php if($ads instanceof \VigattinAds\DomainModel\Ads): ?>
    <div class="row">
        <div class="col-lg-5 col-md-5 col-sm-5 col-xs-5">
            <div class="row ads-frame">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 ads-frame-title"><a target="_blank" href="<?php echo $this->escapeHtmlAttr($ads->get('adsUrl')); ?>"><?php echo $this->escapeHtml($ads->get('adsTitle')); ?></a></div>
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12"><div class="ads-image-preview-container"><img class="ads-frame-image" src="/repo<?php echo $this->escapeHtmlAttr($ads->get('adsImage')); ?>"></div><span class="ads-frame-description"><?php echo $this->escapeHtml($ads->get('adsDescription')); ?></span></div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-5 col-md-5 col-sm-5 col-xs-5">
            <div class="form-group">
                <label class="control-label" for="review-reason"></label>
                <textarea maxlength="1012" class="form-control" id="review-reason" name="review_reason" placeholder="If this advertise did not pass the required criteria, please explain why you disapproved this ads."></textarea>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <button type="submit" name="result" value="approved" class="btn btn-success">Approve</button>
            <button type="submit" name="result" value="disapproved" class="btn btn-danger">Disapprove</button>
            <input type="hidden" name="version" value="<?php echo $ads->get('reviewVersion'); ?>" />
        </div>
    </div>
    <?php else: ?>
    <div class="row">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="alert alert-warning">
                <strong>No Pending Ads</strong> Please click recheck to check if there has pending ads.
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <button type="submit" name="result" value="recheck" class="btn btn-success">Recheck</button>
        </div>
    </div>
    <?php endif; ?>
</form>