<?php if(!($ads instanceof \VigattinAds\DomainModel\Ads)): ?>
<div class="alert alert-danger">No Ads Found!</div>
<?php else: ?>
<div class="alert-box">
    <?php if($ads->get('status') == $ads::STATUS_PENDING): ?>
        <div class="alert auto-hide alert-warning fade in"><button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button><strong>Ads under review!</strong> For now this ads is in pending status, please wait until the review finish.</div>
    <?php elseif($ads->get('status') == $ads::STATUS_DISAPPROVED): ?>
        <div class="alert auto-hide alert-danger fade in"><button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button><strong>Ads Disapproved!</strong> <?php echo $this->escapeHtml($adsReviewReason); ?></div>
        <?php elseif($ads->get('status') == $ads::STATUS_PAUSED): ?>
        <div class="alert auto-hide alert-warning fade in"><button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button><strong>Ads paused!</strong> To continue your ads service please click resume.</div>
    <?php endif; ?>
</div>
<input id="adsId" type="hidden" name="adsId" value="<?php echo $ads->get('id'); ?>" />
<div class="row">
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
        <div>Current Gold <img style="display: none" class="current-gold-progress" src="/assets/vigattinads/img/circle-preloader-2.gif" /><span style="display: none" class="glyphicon glyphicon-ok text-success current-gold-success"></span></div>
        <span class="big-font-3em text-warning current-gold middle-align"><?php echo $adsUser->get('credit'); ?></span> <a href="#" data-toggle="modal" data-target="#addGoldCredit" class="middle-align inline-block hover-do-underline tooltip-enable-right" data-toggle="tooltip" title="Add credit to your gold"><span class="glyphicon glyphicon-plus-sign top-align"></span> <small class="top-align">add gold</small></a>
    </div>
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
        <div>Total View(s)</div>
        <span class="big-font-3em total-views middle-align"><?php echo $adsViewCount; ?></span>
    </div>
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
        <div>Reserve View(s) <img style="display: none" class="views-remaining-progress" src="/assets/vigattinads/img/circle-preloader-2.gif" /><span style="display: none" class="glyphicon glyphicon-ok text-success views-remaining-success"></span></div>
        <span class="big-font-3em text-success middle-align remaining-views"><?php echo $ads->get('viewLimit'); ?></span> <a href="#" data-toggle="modal" data-target="#addViewCredit" class="middle-align inline-block hover-do-underline tooltip-enable-right" data-toggle="tooltip" title="Add credit to your remaining view(s) using your gold points"><span class="glyphicon glyphicon-plus-sign top-align"></span> <small class="top-align">edit reserve</small></a>
    </div>

</div>
<form id="ads-form" class="small" method="post" action="">
    <div class="panel panel-default">
        <div class="panel-heading"><?php switch($ads->get('status')):
                case \VigattinAds\DomainModel\Ads::STATUS_APPROVED: ?>
                    <span class="text-success"><span class="glyphicon glyphicon-ok"></span> Approved</span>
                    <?php break;
                case \VigattinAds\DomainModel\Ads::STATUS_PENDING: ?>
                    <span class="text-warning"><span class="glyphicon glyphicon-warning-sign"></span> Pending</span>
                    <?php break;
                case \VigattinAds\DomainModel\Ads::STATUS_DISAPPROVED: ?>
                    <span class="text-danger"><span class="glyphicon glyphicon-ban-circle"></span> Disapproved</span>
                    <?php break;
                case \VigattinAds\DomainModel\Ads::STATUS_PAUSED: ?>
                    <span class="text-warning"><span class="glyphicon glyphicon-pause"></span> Paused</span>
                    <?php break;
                case \VigattinAds\DomainModel\Ads::STATUS_REVIEWING: ?>
                    <span class="text-warning"><span class="glyphicon glyphicon-search"></span> Reviewing</span>
                    <?php break;
            endswitch; ?></div>
            <div class="panel-body">
            <div class="row">
                <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12"><strong>Ads Preview</strong><p></p></div>
                    <div class="col-lg-2 col-md-2 col-sm-2 col-xs-2"></div>
                    <div class="col-lg-8 col-md-8 col-sm-8 col-xs-8">
                        <div class="row ads-frame">
                            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 ads-frame-title"><?php echo $this->escapeHtmlAttr($ads->get('adsTitle')); ?></div>
                            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 ads-frame-price">Php <span class="price-value"><?php echo $this->escapeHtmlAttr(number_format($ads->get('adsPrice'), 2, '.', '')); ?></span></div>
                            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12"><div class="ads-image-preview-container"><img class="ads-frame-image" src="/repo<?php echo $ads->get('adsImage'); ?>"></div><span class="ads-frame-description"><?php echo $this->escapeHtml($ads->get('adsDescription')); ?></span></div>
                        </div>
                    </div>
                    <div class="col-lg-2 col-md-2 col-sm-2 col-xs-2"></div>
                </div>
                <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
                    <div class="form-group ads-form-title <?php echo $adsTitleError ? 'has-error' : ''; ?>">
                        <label class="control-label" for="ads-title">Ads Title <small id="adsTitleCountDisplay" class="text-warning"></small></label>
                        <span class="help-block"><?php if($adsTitleError) echo $adsTitleError; ?></span>
                        <input type="text" maxlength="60" class="form-control countable-character" data-max-char="60" data-target-display="#adsTitleCountDisplay" id="ads-title" name="ads-title" required="true" placeholder="Ads Title" value="<?php echo $this->escapeHtmlAttr($adsTitle); ?>">
                    </div>
                    <div class="form-group ads-form-url <?php echo $adsUrlError ? 'has-error' : ''; ?>">
                        <label class="control-label" for="ads-url">Ads Url <small class="text-warning">allowed valid url</small></label>
                        <span class="help-block"><?php if($adsUrlError) echo $adsUrlError; ?></span>
                        <input type="text" maxlength="256" class="form-control" id="ads-url" name="ads-url" required="true" placeholder="Ads URL" value="<?php echo $this->escapeHtmlAttr($adsUrl); ?>">
                    </div>

                    <div class="hide form-group ads-form-keyword <?php echo $adsKeywordError ? 'has-error' : ''; ?>">
                        <label class="control-label" for="ads-keyword">Target Keyword <small class="text-warning">max character 48 allowed alphanumeric, space and comma</small></label>
                        <span class="help-block"><?php if($adsKeywordError) echo $adsKeywordError; ?></span>
                        <input type="text" maxlength="48" class="form-control" id="ads-keyword" name="ads-keyword" placeholder="Leave blank to target all" value="<?php echo $this->escapeHtmlAttr($adsKeyword); ?>">
                    </div>

                    <div class="form-group ads-form-keyword <?php echo $adsPriceError ? 'has-error' : ''; ?>">
                        <label class="control-label" for="ads-keyword">Price in Php <small class="text-warning">numbers only no special characters</small></label>
                        <span class="help-block"><?php if($adsPriceError) echo $adsPriceError; ?></span>
                        <input type="number" step="any" class="form-control" id="ads-price" name="ads-price" placeholder="Ads price" value="<?php echo $this->escapeHtmlAttr($adsPrice); ?>">
                    </div>
                    <div class="form-group ads-form-description <?php echo $adsDescriptionError ? 'has-error' : ''; ?>">
                        <label class="control-label" for="ads-description">Ads Description <small id="adsDescriptionCountDisplay" class="text-warning"></small></label>
                        <span class="help-block"><?php if($adsDescriptionError) echo $adsDescriptionError; ?></span>
                        <textarea maxlength="130" class="description-input form-control countable-character" data-max-char="130" data-target-display="#adsDescriptionCountDisplay" id="ads-description" name="ads-description" placeholder="Ads Description"><?php echo $this->escapeHtml($adsDescription); ?></textarea>
                    </div>
                    <div class="row">
                        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
                            <a href="<?php echo $this->escapeHtmlAttr($_SERVER['HTTP_REFERER']); ?>" class="btn btn-default tooltip-enable-top" title="Cancel change and back to ads list">Back</a>
                            <button type="submit" class="btn btn-default tooltip-enable-top" title="Apply change made to ads info" name="submit" value="next">Apply</button>
                        </div>
                        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6 text-right">
                            <?php if($ads->get('status') == $ads::STATUS_APPROVED): ?>
                                <button type="submit" class="btn btn-warning tooltip-enable-top" title="Temporarily stop this ads" name="submit" value="pause" data-toggle="modal" data-target="#pauseAds">Pause</button>
                            <?php elseif($ads->get('status') == $ads::STATUS_PAUSED): ?>
                                <button type="submit" class="btn btn-success tooltip-enable-top" title="Resume advertising this ads" name="submit" value="resume" data-toggle="modal" data-target="#pauseAds">Resume</button>
                            <?php else: ?>
                                <button type="submit" class="btn btn-warning tooltip-enable-top" name="submit" value="noActon" data-toggle="modal" data-target="#pauseAds" disabled="disabled">Pause</button>
                            <?php endif; ?>
                            <button type="submit" class="btn btn-danger tooltip-enable-top" title="Delete this ads" name="submit" value="delete" data-toggle="modal" data-target="#deleteAds">Delete</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>
    <!-- Modal Add Views -->
    <div class="modal fade" id="addViewCredit" tabindex="-1" role="dialog" aria-labelledby="addViewCredit" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title" id="myModalLabel">Add View(s) Credit</h4>
                </div>
                <div class="modal-body">
                    <div class="row">
                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                            <p>Exchange rate Gold to View <span class="viewToGoldRate">0</span></p>
                        </div>
                        <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4">
                            <div>Current Gold</div>
                            <span class="modal-current-gold">0</span>
                        </div>
                        <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4">
                            <div>Current Reserve View(s)</div>
                            <span class="modal-current-reserve-view">0</span>
                        </div>
                        <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4">
                            <div>New Reserve View(s)</div>
                            <input type="number" class="form-control middle-align modal-remaining-views allowed-number-only" value="0" min="0" max="1000000" />
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                    <button id="addViewCreditSave" type="button" disabled="disabled" class="btn btn-primary add-views-save-change">Save changes</button>
                </div>
            </div><!-- /.modal-content -->
        </div><!-- /.modal-dialog -->
    </div><!-- /.modal -->

    <!-- Modal Add Gold -->
    <div class="modal fade" id="addGoldCredit" tabindex="-1" role="dialog" aria-labelledby="addGoldCredit" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title" id="myModalLabel">Add Gold Credit</h4>
                </div>
                <div class="modal-body">

                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                    <button type="button" disabled="disabled" class="btn btn-primary add-views-save-change">Save changes</button>
                </div>
            </div><!-- /.modal-content -->
        </div><!-- /.modal-dialog -->
    </div><!-- /.modal -->

    <!-- Modal Delete Ads -->
    <div class="modal fade" id="deleteAds" tabindex="-1" role="dialog" aria-labelledby="deleteAds" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title text-danger" id="myModalLabel">Are you sure you want to delete this ads?</h4>
                </div>
                <div class="modal-body">
                    <p>This action is un-reversible, all remaining view(s) of this ads will be converted back to gold points.</p>
                </div>
                <div class="modal-footer">
                    <form method="post" action="">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                        <button type="submit" name="submit" value="delete" class="btn btn-danger add-views-save-change">Yes</button>
                    </form>
                </div>
            </div><!-- /.modal-content -->
        </div><!-- /.modal-dialog -->
    </div><!-- /.modal -->

    <?php if($ads->get('status') == $ads::STATUS_PAUSED): ?>
        <!-- Modal Resume Ads -->
        <div class="modal fade" id="pauseAds" tabindex="-1" role="dialog" aria-labelledby="pauseAds" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                        <h4 class="modal-title text-success" id="myModalLabel">Resume advertising this ads ?</h4>
                    </div>
                    <div class="modal-body">
                        <p>This action will resume this ads from appearing from all ads website.</p>
                    </div>
                    <div class="modal-footer">
                        <form method="post" action="">
                            <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                            <button type="submit" name="submit" value="resume" class="btn btn-success add-views-save-change">Yes</button>
                        </form>
                    </div>
                </div><!-- /.modal-content -->
            </div><!-- /.modal-dialog -->
        </div><!-- /.modal -->
    <?php else: ?>
        <!-- Modal Pause Ads -->
        <div class="modal fade" id="pauseAds" tabindex="-1" role="dialog" aria-labelledby="pauseAds" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                        <h4 class="modal-title text-warning" id="myModalLabel">Temporarily stop this ads?</h4>
                    </div>
                    <div class="modal-body">
                        <p>This action will pause this ads from appearing from all ads website.</p>
                    </div>
                    <div class="modal-footer">
                        <form method="post" action="">
                            <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                            <button type="submit" name="submit" value="pause" class="btn btn-warning add-views-save-change">Yes</button>
                        </form>
                    </div>
                </div><!-- /.modal-content -->
            </div><!-- /.modal-dialog -->
        </div><!-- /.modal -->
    <?php endif; ?>
<?php endif; ?>