<form method="post" action="">
    <div class="row">
        <div class="col-sm-6 col-md-4">
            <div class="thumbnail">
                <img src="/assets/vigattinads/img/trade-sidebar.jpg" style="width: 100%" />
                <div class="caption">
                    <h4><a href="http://www.vigattintrade.com">vigattintrade.com</a></h4>
                    <p>Featured Ads.</p>
                    <button type="submit" name="action" value="4" class="btn btn-primary">Choose this</button>
                </div>
            </div>
        </div>
        <div class="col-sm-6 col-md-4">
            <div class="thumbnail">
                <img src="/assets/vigattinads/img/trade-sidebar.jpg" style="width: 100%" />
                <div class="caption">
                    <h4><a href="http://www.vigattintrade.com">vigattintrade.com</a></h4>
                    <p>Home page sidebar.</p>
                    <button type="submit" name="action" value="1" class="btn btn-primary">Choose this</button>
                </div>
            </div>
        </div>
        <div class="col-sm-6 col-md-4">
            <div class="thumbnail">
                <img src="/assets/vigattinads/img/trade-related-ads.jpg" style="width: 100%" />
                <div class="caption">
                    <h4><a href="http://www.vigattintrade.com">vigattintrade.com</a></h4>
                    <p>Related ads bottom page</p>
                    <button type="submit" name="action" value="2" class="btn btn-primary">Choose this</button>
                </div>
            </div>
        </div>
        <div class="col-sm-6 col-md-4">
            <div class="thumbnail">
                <img src="/assets/vigattinads/img/tour-sidebar-right.jpg" style="width: 100%" />
                <div class="caption">
                    <h4><a href="http://www.vigattintourism.com">vigattintourism.com</a></h4>
                    <p>Vigattintrade home page sidebar ads</p>
                    <button type="submit" name="action" value="3" class="btn btn-primary">Choose this</button>
                </div>
            </div>
        </div>
    </div>
</form>