<div class="panel panel-primary ">
    <div class="panel-heading">Edit Ads Info</div>
    <div class="panel-body">
        <form id="ads-form" class="small" role="form" action="" method="post" enctype="multipart/form-data">
            <div class="row">
                <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12"><strong>Ads Preview</strong><p></p></div>
                    <div class="col-lg-2 col-md-2 col-sm-2 col-xs-2"></div>
                    <div class="col-lg-8 col-md-8 col-sm-8 col-xs-8">
                        <div class="row ads-frame">
                            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 ads-frame-title"><?php echo $this->escapeHtmlAttr($adsTitle); ?></div>
                            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12"><div class="ads-image-preview-container"></div><span class="ads-frame-description"><?php echo $this->escapeHtml($adsDescription); ?></span></div>
                        </div>
                    </div>
                    <div class="col-lg-2 col-md-2 col-sm-2 col-xs-2"></div>
                </div>
                <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
                    <div class="form-group ads-form-image <?php echo $adsImageError ? 'has-error' : ''; ?>">
                        <label class="control-label" for="ads-title">Choose an image</label>
                            <span class="help-block"><?php if($adsImageError) echo $adsImageError; ?></span>
                        <input type="file" id="ads-choose-image-input" name="ads-image" accept="image/*" required="true">
                    </div>
                    <div class="form-group ads-form-title <?php echo $adsTitleError ? 'has-error' : ''; ?>">
                        <label class="control-label" for="ads-title">Ads Title <small class="text-warning">(max character 48 allowed alphanumeric, space and .-_'"/,&())</small></label>
                            <span class="help-block"><?php if($adsTitleError) echo $adsTitleError; ?></span>
                        <input type="text" maxlength="48" class="form-control" id="ads-title" name="ads-title" required="true" placeholder="Ads Title" value="<?php echo $this->escapeHtmlAttr($adsTitle); ?>">
                    </div>
                    <div class="form-group ads-form-url <?php echo $adsUrlError ? 'has-error' : ''; ?>">
                        <label class="control-label" for="ads-url">Ads Url <small class="text-warning">(max character 256 allowed valid url)</small></label>
                            <span class="help-block"><?php if($adsUrlError) echo $adsUrlError; ?></span>
                        <input type="text" maxlength="256" class="form-control" id="ads-url" name="ads-url" required="true" placeholder="Ads URL" value="<?php echo $this->escapeHtmlAttr($adsUrl); ?>">
                    </div>
                    <div class="form-group ads-form-keyword <?php echo $adsKeywordError ? 'has-error' : ''; ?>">
                        <label class="control-label" for="ads-keyword">Target Keyword <small class="text-warning">(max character 48 allowed alphanumeric, space and comma)</small></label>
                            <span class="help-block"><?php if($adsKeywordError) echo $adsKeywordError; ?></span>
                        <input type="text" maxlength="48" class="form-control" id="ads-keyword" name="ads-keyword" placeholder="Leave blank to target all" value="<?php echo $this->escapeHtmlAttr($adsKeyword); ?>">
                    </div>
                    <div class="form-group ads-form-description <?php echo $adsDescriptionError ? 'has-error' : ''; ?>">
                        <label class="control-label" for="ads-description">Ads Description <small class="text-warning">(max character 160 allowed alphanumeric, space and .-_'"/,&())</small></label>
                            <span class="help-block"><?php if($adsDescriptionError) echo $adsDescriptionError; ?></span>
                        <textarea maxlength="160" class="description-input form-control" id="ads-description" name="ads-description" placeholder="Ads Description"><?php echo $this->escapeHtml($adsDescription); ?></textarea>
                    </div>
                    <button type="submit" class="btn btn-primary" name="submit" value="next">Submit</button>
                </div>
            </div>
        </form>
    </div>
</div>