<div class="row row-offcanvas row-offcanvas-left">

    <div class="col-xs-6 col-sm-2 sidebar-offcanvas" id="sidebar" role="navigation">
        <div class="list-group">
            <a href="<?php echo ($action == 'index') ? '#' : '/vigattinads/account-home'; ?>" class="list-group-item <?php echo ($action == 'index') ? 'active' : ''; ?>"><span class="glyphicon glyphicon-home"></span>&nbsp;&nbsp;&nbsp;Dashboard</a>
            <a href="<?php echo ($action == 'ads') ? '#' : '/vigattinads/account-home/ads'; ?>" class="list-group-item <?php echo ($action == 'ads') ? 'active' : ''; ?>"><span class="glyphicon glyphicon-eye-open"></span>&nbsp;&nbsp;&nbsp;Ads</a>
            <a href="<?php echo ($action == 'profile') ? '#' : '/vigattinads/account-home/profile'; ?>" class="list-group-item <?php echo ($action == 'profile') ? 'active' : ''; ?>"><span class="glyphicon glyphicon-user"></span>&nbsp;&nbsp;&nbsp;Profile</a>
            <a href="<?php echo ($action == 'admin') ? '#' : '/vigattinads/account-home/admin'; ?>" class="list-group-item <?php echo ($action == 'admin') ? 'active' : ''; ?>"><span class="glyphicon glyphicon-wrench"></span>&nbsp;&nbsp;&nbsp;Admin</a>
        </div>
    </div><!--/span-->

    <div class="col-xs-12 col-sm-10">
        <p class="pull-left visible-xs">
            <button type="button" class="btn btn-primary btn-xs" data-toggle="offcanvas">Toggle nav</button>
        </p>
        <div>
            <div><h3><?php echo $title; ?></h3></div>
            <?php echo $actionContent; ?>
        </div>
    </div><!--/span-->

</div><!--/row-->
