<div>
    <p><a href="/vigattinads/account-home/ads/wizard" class="btn btn-primary"><span class="glyphicon glyphicon-plus"></span> Create New Ads Wizard</a></p>
</div>
<div class="table-responsive">
    <table class="table table-bordered">
        <thead>
        <tr>
            <th>#</th>
            <th>Ads Title</th>
            <th>Status</th>
            <th>Show In</th>
            <th>Position</th>
            <th>Options</th>
        </tr>
        </thead>
        <tbody>
        <?php foreach($adsList as $key => $ads): ?>
        <tr>
            <td><?php echo $key+1; ?></td>
            <td><?php echo $ads->get('adsTitle'); ?></td>
            <td><?php switch($ads->get('status')):
                case \VigattinAds\DomainModel\Ads::STATUS_APPROVED: ?>
                    <span class="text-success"><span class="glyphicon glyphicon-ok"></span> Approved</span>
                    <?php break;
                case \VigattinAds\DomainModel\Ads::STATUS_PENDING: ?>
                    <span class="text-warning"><span class="glyphicon glyphicon-warning-sign"></span> Pending</span>
                    <?php break;
                case \VigattinAds\DomainModel\Ads::STATUS_DISAPPROVED: ?>
                    <span class="text-danger"><span class="glyphicon glyphicon-ban-circle"></span> Disapproved</span>
                    <?php break;
            endswitch; ?></td>
            <td><?php echo $ads->get('showIn'); ?></td>
            <td><?php echo $ads->get('template'); ?></td>
            <td><a href="/vigattinads/account-home/ads/view/<?php echo $ads->get('id'); ?>"><span class="glyphicon glyphicon-edit"></span> View</a></td>
        </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>