<div>
    <p><a href="/vigattinads/account-home/ads/wizard" class="btn btn-primary"><span class="glyphicon glyphicon-plus"></span> Create New Ads Wizard</a></p>
</div>
<div class="table-responsive">
    <table class="table table-bordered">
        <thead>
        <tr>
            <th>#</th>
            <th>Ads ID</th>
            <th>Ads Title</th>
            <th>Status</th>
            <th>Show In</th>
            <th>Position</th>
            <th>Ads Link</th>
            <th>Options</th>
        </tr>
        </thead>
        <tbody>
        <?php foreach($adsList as $ads): ?>
        <tr>
            <td></td>
            <td><?php echo $ads->getId(); ?></td>
            <td><?php echo $ads->getAdsTitle(); ?></td>
            <td><?php echo $userModel->getAds()->translateStatus($ads->getStatus()); ?></td>
            <td><?php echo $ads->getShowIn(); ?></td>
            <td><?php echo $ads->getTemplate(); ?></td>
            <td><?php echo $ads->getAdsUrl(); ?></td>
            <td><a href="/vigattinads/account-home/ads/view/<?php echo $ads->getId(); ?>"><span class="glyphicon glyphicon-edit"></span> View</a></td>
        </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>