<div class="row row-offcanvas row-offcanvas-left">

    <div class="col-xs-6 col-sm-3 sidebar-offcanvas" id="sidebar" role="navigation">
        <div class="list-group">
            <a href="#" class="list-group-item active">My Profile</a>
            <a href="/vigattinads/account-home/my-ads" class="list-group-item">My Ads</a>
            <a href="/vigattinads/account-home/option" class="list-group-item">Option</a>
            <a href="/vigattinads/account-home/about" class="list-group-item">About</a>
        </div>
    </div><!--/span-->

    <div class="col-xs-12 col-sm-9">
        <p class="pull-left visible-xs">
            <button type="button" class="btn btn-primary btn-xs" data-toggle="offcanvas">Toggle nav</button>
        </p>
        <div class="">
            <h3>Profile management</h3>
            <p>This is an example to show the potential of an offcanvas layout pattern in Bootstrap. Try some responsive-range viewport sizes to see it in action.</p>
        </div>
    </div><!--/span-->

</div><!--/row-->
