<div class="sidebar-ads-fbstyle">
    <div class="ads-panel-title">VigattinAds</div>
    <?php foreach($ads as $key => $ad): ?>
        <a href="<?php echo $this->escapeHtmlAttr($ad['adsUrl']); ?>" target="_blank" class="ads-frame <?php echo (count($ads) == ($key+1)) ? 'last' : '';  ?>" id="<?php echo $ad['id']; ?>">
            <div class="ads-frame-title"><?php echo $this->escapeHtml($ad['adsTitle']); ?></div>
            <div class="ads-frame-price">
                <?php if(floatval($ad['adsPrice'])): ?>
                    Php <span class="price-value"><?php echo $this->escapeHtml(number_format($ad['adsPrice'], 2, '.', '')); ?></span>
                <?php endif; ?>
            </div>
            <div class="ads-divided-content"><div class="ads-frame-leftbar">
                <div class="ads-image-preview-container"><img class="ads-frame-image" src="/repo<?php echo $this->escapeHtmlAttr($ad['adsImage']); ?>"></div>
            </div><?php echo $this->escapeHtml($ad['adsDescription']); ?></div>
            <br style="clear: both">
        </a>
        <div class="ads-separator"></div>
    <?php endforeach; ?>
</div>
