<?php /** @var $ad \VigattinAds\Entity\Ads */ ?>
<div class="ads-sidebar-generic">
    <?php foreach($ads as $ad): ?>
        <a href="<?php echo $this->escapeHtmlAttr($ad->get('adsUrl')); ?>" target="_parent" class="ads-frame" id="<?php echo $ad->get('id'); ?>">
            <div class="ads-frame-title"><?php echo $this->escapeHtml($ad->get('adsTitle')); ?></div>
            <div class="ads-content"><div class="ads-image-preview-container"><img class="ads-frame-image" src="/repo<?php echo $this->escapeHtmlAttr($ad->get('adsImage')); ?>"></div><span class="ads-frame-description"><?php echo $this->escapeHtml($ad->get('adsDescription')); ?></span></div>
            <div class="clear-float"></div>
        </a>
        <div class="ads-separator"></div>
    <?php endforeach; ?>
</div>
<!--
<a href="#" class="ads-frame">
    <div class="ads-frame-title">Samsung Galaxy S4 for sale</div>
    <div class="ads-content"><div class="ads-image-preview-container"><img class="ads-frame-image" src="http://www.service.vigattin.com/repo/2013/12/06/10/52a199625a218.jpg"></div><span class="ads-frame-description">This is the cheapest cellphone you can find in the market. So hurry buy now before stock last.</span></div>
    <div class="clear-float"></div>
</a>
<div class="ads-separator"></div>
-->

