<div class="trade-ads-listing"><a href="" class="ads-frame">
            <div class="ads-image-preview-container"><img class="ads-frame-image" src=""></div>
            <div class="title-container">
                <div class="ads-frame-title"></div>
                <div class="ads-frame-description"></div>
            </div>
            <div class="price-container">
                <div class="ads-frame-price"></div>
                <div class="ads-frame-date"></div>
            </div>
</a></div>

<script src="//code.jquery.com/jquery-1.10.2.min.js"></script>
<script>
    $('.ads-frame').attr('href', localStorage.tempAdsUrl);
    $('.ads-frame-title').text(localStorage.tempAdsTitle);
    if(localStorage.tempAdsPrice) $('.ads-frame-price').text('php '+localStorage.tempAdsPrice);
    $('.ads-frame-image').attr('src', localStorage.tempAdsImage);
    $('.ads-frame-description').text(localStorage.tempAdsDescription);
    $('.ads-frame-date').text(localStorage.tempAdsDate);
</script>

