<?php /** @var $ad \VigattinAds\Entity\Ads */ ?>
<?php foreach($ads as $ad): ?>
    <a href="<?php echo $this->escapeHtmlAttr($ad->getAdsUrl()); ?>" target="_parent" class="ads-frame" id="<?php echo $ad->getId(); ?>">
        <div class="ads-frame-title"><?php echo $this->escapeHtml($ad->getAdsTitle()); ?></div>
        <div class="ads-content"><div class="ads-image-preview-container"><img class="ads-frame-image" src="/repo<?php echo $this->escapeHtmlAttr($ad->getAdsImage()); ?>"></div><span class="ads-frame-description"><?php echo $this->escapeHtml($ad->getAdsDescription()); ?></span></div>
        <div class="clear-float"></div>
    </a>
    <div class="ads-separator"></div>
<?php endforeach; ?>
<!--
<a href="#" class="ads-frame">
    <div class="ads-frame-title">Samsung Galaxy S4 for sale</div>
    <div class="ads-content"><div class="ads-image-preview-container"><img class="ads-frame-image" src="http://www.service.vigattin.com/repo/2013/12/06/10/52a199625a218.jpg"></div><span class="ads-frame-description">This is the cheapest cellphone you can find in the market. So hurry buy now before stock last.</span></div>
    <div class="clear-float"></div>
</a>
<div class="ads-separator"></div>
-->

