<div class="trade-sidebar-ads">
    <?php foreach($ads as $key => $ad): ?>
        <a href="<?php echo $this->escapeHtmlAttr($ad->get('adsUrl')); ?>" target="_parent" class="ads-frame <?php echo (count($ads) == ($key+1)) ? 'last' : '';  ?>" id="<?php echo $ad->get('id'); ?>">
            <div class="ads-frame-title"><?php echo $this->escapeHtml($ad->get('adsTitle')); ?></div>
            <div class="ads-divided-content"><div class="ads-frame-leftbar">
                <div class="ads-image-preview-container"><img class="ads-frame-image" src="/repo<?php echo $this->escapeHtmlAttr($ad->get('adsImage')); ?>"></div>
                <div class="ads-frame-price">Php <?php echo $this->escapeHtml($ad->get('adsPrice')); ?></div>
            </div><div class="ads-frame-rightbar">
                <div class="ads-frame-description"><?php echo $this->escapeHtml($ad->get('adsDescription')); ?></div>
            </div></div>
        </a>
        <div class="ads-separator"></div>
    <?php endforeach; ?>
</div>
