<div class="ads-frame">
    <div class="ads-frame-title">Samsung Galaxy S4 for sale</div>
    <div class="ads-content"><div class="ads-image-preview-container"><img class="ads-frame-image" src="http://www.service.vigattin.com/repo/2013/12/06/10/52a199625a218.jpg"></div><span class="ads-frame-description">This is the cheapest cellphone you can find in the market. So hurry buy now before stock last.</span></div>
    <div style="clear: both"></div>
</div>
<div class="ads-frame">
    <div class="ads-frame-title">Samsung Galaxy S4 for sale</div>
    <div class="ads-content"><div class="ads-image-preview-container"><img class="ads-frame-image" src="http://www.service.vigattin.com/repo/2013/12/06/10/52a199625a218.jpg"></div><span class="ads-frame-description">This is the cheapest cellphone you can find in the market. So hurry buy now before stock last.</span></div>
</div>
<div class="ads-frame">
    <div class="ads-frame-title">Samsung Galaxy S4 for sale</div>
    <div class="ads-content"><div class="ads-image-preview-container"><img class="ads-frame-image" src="http://www.service.vigattin.com/repo/2013/12/06/10/52a199625a218.jpg"></div><span class="ads-frame-description">This is the cheapest cellphone you can find in the market. So hurry buy now before stock last.</span></div>
</div>

