<div class="trade-ads-listing tourism-head-ads"><?php foreach($ads as $ad): ?><a href="<?php echo $this->escapeHtmlAttr($ad['adsUrl']); ?>" target="_blank" class="ads-frame" id="<?php echo $ad['id']; ?>">
            <div class="ads-image-preview-container vertical-center-img"><img alt="<?php echo $this->escapeHtmlAttr($ad['adsTitle']); ?>" class="ads-frame-image" src="/repo<?php echo $this->escapeHtmlAttr($ad['adsImage']); ?>"></div>
            <div class="title-container">
                <div class="ads-frame-title"><?php echo $this->escapeHtml($ad['adsTitle']); ?></div>
                <div class="ads-frame-description"><?php echo $this->escapeHtml($ad['adsDescription']); ?></div>
            </div>
            <div class="price-container">
                <div class="ads-frame-price">
                    <?php if(floatval($ad['adsPrice'])): ?>
                        Php <?php echo $this->escapeHtml(number_format($ad['adsPrice'], 2, '.', ',')); ?>
                    <?php endif; ?>
                </div>
                <div class="ads-frame-date">
                    <?php echo $this->escapeHtml($ad['date']); ?>
                </div>
            </div>
</a><?php endforeach; ?></div>

