<div class="trade-featured-ads"><?php foreach($ads as $ad): ?><a href="<?php echo $this->escapeHtmlAttr($ad->get('adsUrl')); ?>" target="_blank" class="ads-frame" id="<?php echo $ad->get('id'); ?>">
            <div class="ads-image-preview-container"><img alt="<?php echo $this->escapeHtmlAttr($ad->get('adsTitle')); ?>" class="ads-frame-image" src="/repo<?php echo $this->escapeHtmlAttr($ad->get('adsImage')); ?>"></div>
            <div class="ads-frame-title"><?php echo $this->escapeHtml($ad->get('adsTitle')); ?></div>
            <div class="ads-frame-price">
                <?php if(floatval($ad->get('adsPrice'))): ?>
                Php <?php echo $this->escapeHtml(number_format($ad->get('adsPrice'), 2, '.', ',')); ?>
                <?php endif; ?>
            </div>
</a><?php endforeach; ?></div>

