<?php if(!($ads instanceof \VigattinAds\DomainModel\Ads)): ?>
<div class="alert alert-danger">No Ads Found!</div>
<?php else: ?>
<div class="alert fade in ajax-result-alert">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
    <strong class="title"></strong> <span class="message"></span>
</div>
<input id="adsId" type="hidden" name="adsId" value="<?php echo $ads->get('id'); ?>" />
<div class="row">
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
        <div>Current Gold <img class="current-gold-progress" src="/assets/vigattinads/img/circle-preloader-2.gif" /></div>
        <span class="big-font-3em text-warning current-gold middle-align"><?php echo $adsUser->get('credit'); ?></span> <a href="#" data-toggle="modal" data-target="#addGoldCredit" class="middle-align inline-block hover-do-underline tooltip-enable-right" data-toggle="tooltip" title="Add credit to your gold"><span class="glyphicon glyphicon-plus-sign top-align"></span> <small class="top-align">add credit</small></a>
    </div>
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
        <div>Total View(s)</div>
        <span class="big-font-3em total-views middle-align"><?php echo $adsViewCount; ?></span>
    </div>
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
        <div>View(s) Remaining <img class="views-remaining-progress" src="/assets/vigattinads/img/circle-preloader-2.gif" /></div>
        <span class="big-font-3em text-success middle-align remaining-views"><?php echo $ads->get('viewLimit'); ?></span> <a href="#" data-toggle="modal" data-target="#addViewCredit" class="middle-align inline-block hover-do-underline tooltip-enable-right" data-toggle="tooltip" title="Add credit to your remaining view(s) using your gold points"><span class="glyphicon glyphicon-plus-sign top-align"></span> <small class="top-align">add credit</small></a>
    </div>

</div>
<form class="small" method="post" action="">
    <div class="panel panel-info ">
        <div class="panel-heading"><?php switch($ads->get('status')):
                case \VigattinAds\DomainModel\Ads::STATUS_APPROVED: ?>
                    <span class="text-success"><span class="glyphicon glyphicon-ok"></span> Approved</span>
                    <?php break;
                case \VigattinAds\DomainModel\Ads::STATUS_PENDING: ?>
                    <span class="text-warning"><span class="glyphicon glyphicon-warning-sign"></span> Pending</span>
                    <?php break;
                case \VigattinAds\DomainModel\Ads::STATUS_DISAPPROVED: ?>
                    <span class="text-danger"><span class="glyphicon glyphicon-ban-circle"></span> Disapproved</span>
                    <?php break;
            endswitch; ?></div>
            <div class="panel-body">
            <div class="row">
                <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12"><strong>Ads Preview</strong><p></p></div>
                    <div class="col-lg-2 col-md-2 col-sm-2 col-xs-2"></div>
                    <div class="col-lg-8 col-md-8 col-sm-8 col-xs-8">
                        <div class="row ads-frame">
                            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 ads-frame-title"><?php echo $this->escapeHtmlAttr($ads->get('adsTitle')); ?></div>
                            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12"><div class="ads-image-preview-container"><img class="ads-frame-image" src="/repo<?php echo $ads->get('adsImage'); ?>"></div><span class="ads-frame-description"><?php echo $this->escapeHtml($ads->get('adsDescription')); ?></span></div>
                        </div>
                    </div>
                    <div class="col-lg-2 col-md-2 col-sm-2 col-xs-2"></div>
                </div>
                <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
                    <div class="form-group <?php echo $adsTitleError ? 'has-error' : ''; ?>">
                        <label class="control-label" for="ads-title">Ads Title <small class="text-warning">(max character 48 allowed alphanumeric, space and .-_'"/,&())</small></label>
                        <?php if($adsTitleError): ?>
                            <span class="help-block"><?php echo $adsTitleError; ?></span>
                        <?php endif ?>
                        <input type="text" maxlength="48" class="form-control" id="ads-title" name="ads-title" required="true" placeholder="Ads Title" value="<?php echo $this->escapeHtmlAttr($ads->get('adsTitle')); ?>">
                    </div>
                    <div class="form-group <?php echo $adsUrlError ? 'has-error' : ''; ?>">
                        <label class="control-label" for="ads-url">Ads Url <small class="text-warning">(max character 256 allowed valid url)</small></label>
                        <?php if($adsUrlError): ?>
                            <span class="help-block"><?php echo $adsUrlError; ?></span>
                        <?php endif ?>
                        <input type="text" maxlength="256" class="form-control" id="ads-url" name="ads-url" required="true" placeholder="Ads URL" value="<?php echo $this->escapeHtmlAttr($ads->get('adsUrl')); ?>">
                    </div>
                    <div class="form-group <?php echo $adsKeywordError ? 'has-error' : ''; ?>">
                        <label class="control-label" for="ads-keyword">Target Keyword <small class="text-warning">(max character 48 allowed alphanumeric, space and comma)</small></label>
                        <?php if($adsKeywordError): ?>
                            <span class="help-block"><?php echo $adsKeywordError; ?></span>
                        <?php endif ?>
                        <input type="text" maxlength="48" class="form-control" id="ads-keyword" name="ads-keyword" placeholder="Leave blank to target all" value="<?php echo $this->escapeHtmlAttr($ads->get('keywords')); ?>">
                    </div>
                    <div class="form-group <?php echo $adsDescriptionError ? 'has-error' : ''; ?>">
                        <label class="control-label" for="ads-description">Ads Description <small class="text-warning">(max character 160 allowed alphanumeric, space and .-_'"/,&())</small></label>
                        <?php if($adsDescriptionError): ?>
                            <span class="help-block"><?php echo $adsDescriptionError; ?></span>
                        <?php endif ?>
                        <textarea maxlength="160" class="description-input form-control" id="ads-description" name="ads-description" placeholder="Ads Description"><?php echo $this->escapeHtml($ads->get('adsDescription')); ?></textarea>
                    </div>
                    <button type="submit" class="btn btn-primary" name="submit" value="next">Update</button>
                </div>
            </div>
        </div>
    </div>
</form>
    <!-- Modal Add Views -->
    <div class="modal fade" id="addViewCredit" tabindex="-1" role="dialog" aria-labelledby="addViewCredit" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title" id="myModalLabel">Add View(s) Credit</h4>
                </div>
                <div class="modal-body">
                    <div class="row">
                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                            <p>Exchange rate Gold to View <span class="viewToGoldRate">0</span></p>
                        </div>
                        <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4">
                            <div>Current Gold</div>
                            <span class="modal-current-gold">0</span>
                        </div>
                        <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4">
                            <div>Views Remaining</div>
                            <span class="modal-after-view-remaining">0</span>
                        </div>
                        <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4">
                            <div>Add Views</div>
                            <input type="number" class="form-control middle-align modal-remaining-views allowed-number-only" value="0" min="0" max="1000000" />
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    <button id="addViewCreditSave" type="button" disabled="disabled" class="btn btn-primary add-views-save-change">Save changes</button>
                </div>
            </div><!-- /.modal-content -->
        </div><!-- /.modal-dialog -->
    </div><!-- /.modal -->

    <!-- Modal Add Gold -->
    <div class="modal fade" id="addGoldCredit" tabindex="-1" role="dialog" aria-labelledby="addGoldCredit" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title" id="myModalLabel">Add Gold Credit</h4>
                </div>
                <div class="modal-body">

                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    <button type="button" disabled="disabled" class="btn btn-primary add-views-save-change">Save changes</button>
                </div>
            </div><!-- /.modal-content -->
        </div><!-- /.modal-dialog -->
    </div><!-- /.modal -->
<?php endif; ?>