<div class="panel panel-default col-lg-7 col-md-7">
    <div class="panel-heading">Edit Ads Info</div>
    <div class="panel-body">
        <form class="small" role="form" action="" method="post">
            <div class="form-group <?php echo $adsNameError ? 'has-error' : ''; ?>">
                <label class="control-label" for="ads-name">Ads Name</label>
                <?php if($adsNameError): ?>
                    <span class="help-block"><?php echo $adsNameError; ?></span>
                <?php endif ?>
                <input type="text" class="form-control" id="ads-name" name="ads-name" required="true" placeholder="Ads Name" value="<?php echo $this->escapeHtmlAttr($adsName); ?>">
            </div>
            <div class="form-group <?php echo $adsUrlError ? 'has-error' : ''; ?>">
                <label class="control-label" for="ads-url">Ads Url</label>
                <?php if($adsUrlError): ?>
                    <span class="help-block"><?php echo $adsUrlError; ?></span>
                <?php endif ?>
                <input type="text" class="form-control" id="ads-url" name="ads-url" required="true" placeholder="Ads URL" value="<?php echo $this->escapeHtmlAttr($adsUrl); ?>">
            </div>
            <div class="form-group <?php echo $adsDescriptionError ? 'has-error' : ''; ?>">
                <label class="control-label" for="ads-description">Ads Description</label>
                <?php if($adsDescriptionError): ?>
                    <span class="help-block"><?php echo $adsDescriptionError; ?></span>
                <?php endif ?>
                <textarea class="description-input form-control" id="ads-description" name="ads-description" placeholder="Ads Description"><?php echo $this->escapeHtml($adsDescription); ?></textarea>
            </div>
            <button type="submit" class="btn btn-default" name="submit" value="next">Next</button>
        </form>
    </div>
</div>