<form method="post" action="/vigattinads/account-home/ads/wizard/edit">
    <div class="row">
        <div class="col-sm-6 col-md-4">
            <div class="panel panel-primary" >
                <div class="panel-heading">
                    <h3 class="panel-title">Top banner</h3>
                </div>
                <div class="panel-body" >
                    <div>
                        <img src="/assets/vigattinads/img/test1.jpg" style="width: 100%" />
                    </div>
                    <button type="submit" name="action" value="1" class="btn btn-primary">Choose this</button>
                </div>
            </div>
        </div>
        <div class="col-sm-6 col-md-4">
            <div class="panel panel-primary" >
                <div class="panel-heading">
                    <h3 class="panel-title">Left side bar</h3>
                </div>
                <div class="panel-body" >
                    <div>
                        <img src="/assets/vigattinads/img/ads-left-sidebar.jpg" />
                    </div>
                    <button type="submit" name="action" value="2" class="btn btn-primary">Choose this</button>
                </div>
            </div>
        </div>
        <div class="col-sm-6 col-md-4">
            <div class="panel panel-primary" >
                <div class="panel-heading">
                    <h3 class="panel-title">Bottom banner</h3>
                </div>
                <div class="panel-body" >
                    <div>
                        <img src="/assets/vigattinads/img/ads-bottombar.jpg" />
                    </div>
                    <button type="submit" name="action" value="3" class="btn btn-primary">Choose this</button>
                </div>
            </div>
        </div>
    </div>
</form>