<div class="panel panel-primary ">
    <div class="panel-heading">Edit Ads Info</div>
    <div class="panel-body">
        <form class="small" role="form" action="" method="post" enctype="multipart/form-data">
            <div class="row">
                <div class="col-sm-6">
                    <div class="form-group <?php echo $adsImageError ? 'has-error' : ''; ?>">
                        <label class="control-label" for="ads-title">Choose an image</label>
                        <?php if($adsImageError): ?>
                            <span class="help-block"><?php echo $adsImageError; ?></span>
                        <?php endif ?>
                        <input type="file" class="form-control" id="ads-choose-image-input" name="ads-image" accept="image/*" required="true">
                        <p></p>
                        <p id="ads-image-preview-container"></p>
                    </div>
                </div>
                <div class="col-sm-6">
                    <div class="form-group <?php echo $adsTitleError ? 'has-error' : ''; ?>">
                        <label class="control-label" for="ads-title">Ads Title</label>
                        <?php if($adsTitleError): ?>
                            <span class="help-block"><?php echo $adsTitleError; ?></span>
                        <?php endif ?>
                        <input type="text" class="form-control" id="ads-title" name="ads-title" required="true" placeholder="Ads Title" value="<?php echo $this->escapeHtmlAttr($adsTitle); ?>">
                    </div>
                    <div class="form-group <?php echo $adsUrlError ? 'has-error' : ''; ?>">
                        <label class="control-label" for="ads-url">Ads Url</label>
                        <?php if($adsUrlError): ?>
                            <span class="help-block"><?php echo $adsUrlError; ?></span>
                        <?php endif ?>
                        <input type="text" class="form-control" id="ads-url" name="ads-url" required="true" placeholder="Ads URL" value="<?php echo $this->escapeHtmlAttr($adsUrl); ?>">
                    </div>
                    <div class="form-group <?php echo $adsKeywordError ? 'has-error' : ''; ?>">
                        <label class="control-label" for="ads-keyword">Target Keyword</label>
                        <?php if($adsKeywordError): ?>
                            <span class="help-block"><?php echo $adsKeywordError; ?></span>
                        <?php endif ?>
                        <input type="text" class="form-control" id="ads-keyword" name="ads-keyword" placeholder="Leave blank to target all" value="<?php echo $this->escapeHtmlAttr($adsKeyword); ?>">
                    </div>
                    <div class="form-group <?php echo $adsDescriptionError ? 'has-error' : ''; ?>">
                        <label class="control-label" for="ads-description">Ads Description</label>
                        <?php if($adsDescriptionError): ?>
                            <span class="help-block"><?php echo $adsDescriptionError; ?></span>
                        <?php endif ?>
                        <textarea class="description-input form-control" id="ads-description" name="ads-description" placeholder="Ads Description"><?php echo $this->escapeHtml($adsDescription); ?></textarea>
                    </div>
                    <button type="submit" class="btn btn-primary" name="submit" value="next">Submit</button>
                </div>
            </div>
        </form>
    </div>
</div>