<?php echo $this->doctype(); ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Vigattin Ads')->setSeparator(' | ')->setAutoEscape(false); ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge'); ?>

        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
            ->prependStylesheet('//netdna.bootstrapcdn.com/bootstrap/3.0.2/css/bootstrap.min.css')
            ->prependStylesheet('//netdna.bootstrapcdn.com/bootstrap/3.0.2/css/bootstrap-theme.min.css')
            ->prependStylesheet($this->basePath() . '/assets/vigattinads/css/default.css?v='.$config['vigattinads']['assets_version']); ?>
    </head>
    <body
        <!-- Fixed navbar -->
        <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="/vigattinads">Vigattin Ads</a>
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav navbar-right">
                        <li><a href="/vigattinads/logout">Logout</a></li>
                    </ul>
                </div><!--/.nav-collapse -->
            </div>
        </div>
        <div class="container">
            <?php echo $content; ?>
            <hr>
        </div>
        <footer>
            <p class="text-center">&copy; vigattin 2013</p>
        </footer>
        <?php echo $this->headScript()
            ->appendScript('var vauthId = '.$vauthId)
            ->appendScript(isset($js) ? $js : '')
            ->appendFile('//code.jquery.com/jquery-1.10.2.min.js')
            ->appendFile('//netdna.bootstrapcdn.com/bootstrap/3.0.2/js/bootstrap.min.js')
            ->appendFile($this->basePath().'/assets/vigattinads/js/global.js?v='.$config['vigattinads']['assets_version']); ?>
    </body>
</html>
