<?php echo $this->doctype(); ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Vigattin Ads')->setSeparator(' | ')->setAutoEscape(false); ?>
        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge'); ?>
        <!-- <meta http-equiv="refresh" content="180"> -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
            ->appendStylesheet($this->basePath().'/css/bootstrap.min.css')
            ->appendStylesheet($this->basePath().'/css/bootstrap-theme.min.css')
            ->appendStylesheet($this->basePath().'/assets/vigattinads/css/ads.css?v='.$config['vigattinads']['assets_version']); ?>
    </head>
    <body style="background-color: <?php echo $this->escapeHtmlAttr($bgcolor); ?>">
        <div class="container">
            <?php echo $content; ?>
        </div>

        <?php echo $this->headScript()
            ->appendScript(isset($js) ? $js : '')
            ->appendFile($this->basePath().'/js/jquery.min.js')
            ->appendFile($this->basePath().'/js/bootstrap.min.js')
            ->appendFile($this->basePath().'/js/html5shiv.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->appendFile($this->basePath().'/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->appendFile($this->basePath().'/assets/vigattinads/js/ads.js?v='.$config['vigattinads']['assets_version']); ?>
    </body>
</html>
