<?php echo $this->doctype(); ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>Vigattin Ads</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <!-- <meta http-equiv="refresh" content="180"> -->
        <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.0.2/css/bootstrap.min.css">
        <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.0.2/css/bootstrap-theme.min.css">
        <link rel="stylesheet" href="/assets/vigattinads/css/ads.css?v=<?php echo $config['vigattinads']['assets_version']; ?>">
    </head>
    <body style="background-color: <?php echo $this->escapeHtmlAttr($bgcolor); ?>">
        <div class="container">
            <?php echo $content; ?>
        </div>
        <script><?php echo isset($js) ? $js : ''; ?></script>
        <script src="//code.jquery.com/jquery-1.10.2.min.js"></script>
        <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.2/js/bootstrap.min.js"></script>
        <script src="/assets/vigattinads/js/ads.js?v=<?php echo $config['vigattinads']['assets_version']; ?>"></script>
    </body>
</html>
