<?php echo $this->doctype(); ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Vigattin Ads')->setSeparator(' | ')->setAutoEscape(true); ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge'); ?>

        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
            ->appendStylesheet($this->basePath().'/css/bootstrap.min.css')
            ->appendStylesheet($this->basePath().'/css/bootstrap-theme.min.css')
            ->appendStylesheet($this->basePath().'/assets/vigattinads/css/default.css?v='.$config['vigattinads']['assets_version']); ?>
    </head>
    <body>
        <!-- Fixed navbar -->
        <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="#">Vigattin Ads</a>
                </div>
                <div class="navbar-collapse collapse">
                </div><!--/.nav-collapse -->
            </div>
        </div>
        <div class="container">
            <?php echo $content; ?>
            <hr>
            <footer>
                <p class="text-center">&copy; vigattin 2013</p>
            </footer>
        </div>
        <?php echo $this->headScript()
            ->appendScript(isset($js) ? $js : '')
            ->appendFile($this->basePath().'/js/jquery.min.js')
            ->appendFile($this->basePath().'/js/bootstrap.min.js')
            ->appendFile($this->basePath().'/js/html5shiv.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->appendFile($this->basePath().'/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->appendFile($this->basePath().'/assets/vigattinads/js/global.js?v='.$config['vigattinads']['assets_version']); ?>
    </body>
</html>
