<?php echo $this->doctype(); ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Vigattin Ads')->setSeparator(' | ')->setAutoEscape(false); ?>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
        <link rel="stylesheet" href="/assets/vigattinads/css/default.css?v=<?php echo $config['vigattinads']['assets_version']; ?>">
    </head>
    <body>
        <!-- Fixed navbar -->
        <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="#">Vigattin Ads</a>
                </div>
                <div class="navbar-collapse collapse">
                </div><!--/.nav-collapse -->
            </div>
        </div>
        <div class="container">
            <?php echo $content; ?>
            <hr>
            <footer>
                <p class="text-center">&copy; vigattin 2013</p>
            </footer>
        </div>
        <script src="//code.jquery.com/jquery-1.10.2.min.js"></script>
        <script src="//netdna.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
        <script src="/assets/vigattinads/js/global.js?v=<?php echo $config['vigattinads']['assets_version']; ?>"></script>
    </body>
</html>
