<div class="row">
    <div class="col-xs-3">
        <iframe class="vigattinads-frame" data-showin="Vigattin Tourism Article" data-template="home-sidebar-right" style="height: 943px; width: 230px; border: none; background-color: #F0EECB" src="<?php echo $this->escapeHtmlAttr('http://www.service.vigattin.com/vigattinads/showads2/tourism-article/side?showin=vigattin tourism article&template=article&limit=6&keyword=(tourism article rightside 56)'); ?>"></iframe>
    </div>
    <div class="col-xs-9">
        <!--
        <iframe class="vigattinads-frame" data-showin="Vigattin Tourism Article" data-template="home-sidebar-left" scrolling="no" style="height: 111px; width: 672px; overflow: hidden; border: none; background-color: #F0EECB; vertical-align: top" data-action="trade-ads-listing" data-root-keyword="Ads Listing" data-limit="1" src="<?php echo $this->escapeHtmlAttr('http://www.service.vigattin.com/vigattinads/showads2/tourism-article/head?showin=vigattin tourism article&template=article&limit=1&keyword=(tourism article header 56)'); ?>"></iframe>
        -->
        <iframe class="vigattinads-frame" data-showin="Vigattin Tourism Article" scrolling="no" style="height: 111px; width: 672px; overflow: hidden; border: none; background-color: #F0EECB; vertical-align: top" src="<?php echo $this->escapeHtmlAttr('http://www.service.vigattin.com/vigattinads/showads2/tourism-article/head?showin=vigattin tourism article&template=article&limit=1&keyword=(tourism article header 98)'); ?>"></iframe>
    </div>
</div>