<div class="row">
    <div class="col-xs-3">
        <div>vigattin-tourism-article (tourism article rightside 40)</div>
        <iframe class="vigattinads-frame" style="height: 400px; width: 230px; border: none; background-color: #F0EECB" src="<?php echo $this->escapeHtmlAttr('http://www.service.vigattin.com/vigattinads/showads2/tourism-article/side?showin=vigattin-tourism-article&limit=2&keyword=(tourism article rightside 40)'); ?>"></iframe>
    </div>
    <div class="col-xs-3">
        <div>vigattintourism.com (homepage)</div>
        <iframe class="vigattinads-frame" style="height: 400px; width: 230px; border: none; background-color: #F0EECB" src="<?php echo $this->escapeHtmlAttr('http://www.service.vigattin.com/vigattinads/showads2/tourism-article/side?showin=vigattintourism.com&limit=2&keyword=(homepage)'); ?>"></iframe>
    </div>
    <div class="col-xs-3">
        <div>vigattintrade.com (homepage)</div>
        <iframe class="vigattinads-frame" style="height: 400px; width: 230px; border: none; background-color: #F0EECB" src="<?php echo $this->escapeHtmlAttr('http://www.service.vigattin.com/vigattinads/showads2/tourism-article/side?showin=vigattintourism.com&limit=2&keyword=(homepage)'); ?>"></iframe>
    </div>
    <div class="col-xs-3">
    </div>

    <div class="clearfix"></div>

    <div class="col-xs-6">
        <div>vigattin-tourism-article (tourism article header 40)</div>
        <iframe class="vigattinads-frame" data-showin="Vigattin Tourism Article" scrolling="no" style="height: 111px; width: 100%; overflow: hidden; border: none; background-color: #F0EECB; vertical-align: top" src="<?php echo $this->escapeHtmlAttr('http://www.service.vigattin.com/vigattinads/showads2/tourism-article/head?showin=vigattin-tourism-article&limit=1&keyword=(tourism article header 40)'); ?>"></iframe>
    </div>
    <div class="col-xs-6">
        <div>vigattintrade.com (ads listing homepage)</div>
        <iframe class="vigattinads-frame" scrolling="no" style="height: 111px; width: 100%; overflow: hidden; border: none; background-color: #F0EECB; vertical-align: top" data-limit="1" src="http://www.service.vigattin.com/vigattinads/showads/trade-ads-listing?showin=vigattintrade.com&limit=1&keyword=(ads listing homepage)"></iframe>
    </div>
</div>